opt/libexec/

diff --git a/gabrielfalcao/opt/libexec/dns-server b/gabrielfalcao/opt/libexec/dns-server
--- a/gabrielfalcao/opt/libexec/dns-server
+++ b/gabrielfalcao/opt/libexec/dns-server
@@ -1,4 +1,17 @@
 #!/usr/bin/env bash
+export PATH=/opt/homebrew/bin:/Users/gabrielfalcao/opt/libexec:/Users/gabrielfalcao/.elixir-install/installs/otp/27.1.2/bin:/Users/gabrielfalcao/.elixir-install/installs/elixir/1.18.2-otp-27/bin:/Users/gabrielfalcao/.cargo/bin:/Users/gabrielfalcao/.local/bin:/Users/gabrielfalcao/.shell.d/.venv/bin:/Users/gabrielfalcao/.nvm/versions/node/v22.18.0/bin:/opt/homebrew/Cellar/gnu-sed/4.9/libexec/gnubin:/opt/homebrew/Cellar/findutils/4.10.0/libexec/gnubin:/Users/gabrielfalcao/.dotnet/tools:/opt/homebrew/sbin:/Users/gabrielfalcao/.bun/bin:/Users/gabrielfalcao/.deno/bin:/Users/gabrielfalcao/go/install/1.25.0/go/bin:/opt/homebrew/Cellar/bzip2/1.0.8/bin:/opt/homebrew/Cellar/coreutils/9.5/libexec/gnubin:/opt/homebrew/Cellar/curl/8.10.1/bin:/opt/homebrew/Cellar/gnu-tar/1.34_1/libexec/gnubin:/opt/homebrew/Cellar/gnu-time/1.9/libexec/gnubin:/opt/homebrew/Cellar/make/4.4.1/libexec/gnubin:/opt/homebrew/Cellar/openssl@3/3.3.2/bin:/Users/gabrielfalcao/go/bin:/Users/gabrielfalcao/.zig:/opt/g/libexec:/opt/libexec:/bin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Ghostty.app/Contents/MacOS:./tools:./scripts:./node_modules/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:$PATH
+
+export IFS=$'\n'
+set -umeTE
+set +f
+set -o pipefail
+unset IFS
+umask 000
+
+script_name="$(basename "${BASH_SOURCE[0]}")"
+script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
+this_script_path="${script_path}/${script_name}"
+
 
 if [ "$(whoami)" != "root" ]; then
     sudo $0 $@
@@ -7,16 +20,32 @@ fi
 unset IFS
 set -e
 
+declare -a main_argv=($@)
+declare -i main_argc=${#main_argv[@]}
+declare -i code=0
 set -o pipefail
 error_prefix_color_rgb="$((0xFF));$((0x00));$((0x42))"
 error_color_rgb="$((0xFF));$((0x32));$((0x32))"
 error_color_rgb="$((0xFF));$((0x3E));$((0x5C))"
 warn_prefix_color_rgb="$((0xFF));$((0x6A));$((0x32))"
 warn_color_rgb="$((0xFF));$((0xA1));$((0x32))"
+declare -i now=$(date +%s)
+declare -i report_status_running=1
+declare -- dnsmasq_log_path=/var/log/dnsmasq.log
+declare -- function_log_dir="$HOME/opt/var/log/dns-server"
+declare -- stderr="${function_log_dir}/stderr.${now}.log"
+declare -- dnsmasq_conf_path=/opt/homebrew/etc/dnsmasq.07e80a212e0704.conf
+declare -- conf_parent_path=$(dirname "${dnsmasq_conf_path}")
+declare -- conf_filename=$(basename "${dnsmasq_conf_path}")
 
-declare dnsmasq_log_path=/var/log/dnsmasq.log
-
+mkdir -p "${function_log_dir}"
 on_exit() {
+    chown -R gabrielfalcao ${function_log_dir} /opt/homebrew/etc/
+    find ${dnsmasq_log_path} -type d -exec chmod 755 {} \;
+    find ${dnsmasq_log_path} -type f -exec chmod 755 {} \;
+    find ${function_log_dir} -type d -exec chmod 755 {} \;
+    find ${function_log_dir} -type f -exec chmod 755 {} \;
+
     2>/dev/random stty sane
 }
 on_ctrlc() {
@@ -47,17 +76,20 @@ function execute-if-exists() {
     fi
 }
 extract_domain() {
-    name=$(sed -E 's,^(https?://)?([^/]+)([/].*)?$,\2,g' <<< "${name}")
-
+    name=$(sed -E 's,^(https?://)?([^/]+)([/].*)?$,\2,g' <<< "${@}")
+    echo "${name}"
 }
 stop() {
-    2>/dev/null 1>/dev/null g p -qr dns -k
+    2>/dev/null 1>/dev/null g p -qr dnsmasq -k
     2>/dev/null 1>/dev/null g p -qr tcpdump -k
     1>&2 echo -e "dns-server stopped"
 }
 
 server_pids() {
     export IFS=$'\n'
+    # 1>&2 echo -e "\x1b[1;38;5;220m${FUNCNAME[@]@A}\x1b[0m"
+    # 1>&2 echo -e "\x1b[1;38;5;231m${LINENO[@]@A}\x1b[0m"
+    # 1>&2 echo -e "\x1b[1;38;5;242m${BASH_LINENO[@]@A}\x1b[0m"
     local -a running=($(ps aux | grep -v grep | grep -E '/opt/dnsmasq/sbin/dnsmasq' | awk '{print $2}'))
     unset IFS
     if [ ${#running[@]} -eq 0 ]; then
@@ -68,8 +100,9 @@ server_pids() {
 start_bg() {
     local -a pids=()
     local -i server_pid=0
+    local -- stderr=$(mktemp)
     if ! pids=($(server_pids)); then
-        if ! dnsmasq --test -C /opt/homebrew/etc/dnsmasq.conf; then
+        if ! validate_main_conf; then
             return 1
         fi
         /opt/homebrew/opt/dnsmasq/sbin/dnsmasq '--keep-in-foreground' '-C' '/opt/homebrew/etc/dnsmasq.conf' '-7' '/opt/homebrew/etc/dnsmasq.d,*.conf' &
@@ -82,7 +115,7 @@ start_bg() {
 }
 wait_activity() {
     local -i timeout_secs=10
-    local -i started_ts=$(date +%s)
+    local -i started_ts=${now}
     local -i current_ts=${started_ts}
     local -i prev_count=$(cat /var/log/dnsmasq.log | wc -l)
     local -i curr_count=${prev_count}
@@ -92,7 +125,7 @@ wait_activity() {
         curr_count=$(cat /var/log/dnsmasq.log | wc -l)
         1>&2 echo -e "waiting for dnsmasq log activity"
         2>/dev/null 1>/dev/null /usr/bin/curl --max-time ${interval} --connect-timeout ${interval} --expect100-timeout ${interval} --happy-eyeballs-timeout-ms ${interval} -q "https://nsa.gov" || sleep ${interval}
-        current_ts=$(date +%s)
+        current_ts=${now}
     done
     local -i elapsed_seconds=$(( $current_ts - $started_ts ))
     if [ ${elapsed_seconds} -gt ${timeout_secs} ]; then
@@ -103,19 +136,34 @@ wait_activity() {
 }
 start() {
     local -a pids=()
+    pids=($(server_pids))
     local -i started=0
-    until pids=($(server_pids)) && [ ${#pids[@]} -gt 0 ]; do
+    # local -i started=${#pids[@]}
+
+    until [ ${#pids[@]} -gt 0 ]; do
         if ! (( $started )); then
             start_bg
             started=1
         fi
         wait_activity
+        pids=($(server_pids))
     done
-    if pids=($(server_pids)) && [ ${#pids[@]} -gt 0 ]; then
+    if [ ${#pids[@]} -gt 0 ] && (( $report_status_running )); then
         1>&2 echo -e "dns-server running"
+        report_status_running=0
     fi
 }
+validate_main_conf() {
+    local -- stderr=$(mktemp)
+    local -i code=0
+    if ! 2>${stderr} dnsmasq --test -C /opt/homebrew/etc/dnsmasq.conf; then
+        1>&2 echo -e "dnsmasq config error: $(cat ${stderr})"
+        code=$?
+    fi
+    return ${code}
+}
 restart() {
+
     logrotate_path="/var/log/dnsmasq.$(now).log"
     if [ -r "${dnsmasq_log_path}" ] || [ -s "${dnsmasq_log_path}" ]; then
         mv -f "${dnsmasq_log_path}" "$logrotate_path"
@@ -124,9 +172,8 @@ restart() {
         touch "${dnsmasq_log_path}"
         chmod 644 "${dnsmasq_log_path}"
     fi
-    dnsmasq --test -C /opt/homebrew/etc/dnsmasq.conf \
+    validate_main_conf \
         && stop \
-        && start \
         && start \
         && refresh $@
     if [ -f "${logrotate_path}" ]; then
@@ -139,38 +186,49 @@ restart_help() {
 }
 
 logs() {
+    local -a argv=($@)
+    local -i argc=${#argv[@]}
+    local -i index=0
+    local -i current=0
+    local -- arg=""
+
+
+
     if [ -f "${dnsmasq_log_path}" ]; then
         chmod 644 "${dnsmasq_log_path}"
     else
         1>&2 echo -e "cannot read dnsmasq logs, file does not exist: ${log_path@Q}"
         exit 1
     fi
-    local -i amount=0
+    local -i amount=37
 
-    if 1>/dev/random ack '^[0-9]+$' <<< "${1}"; then
-        local -i amount="${1}"
+    if [ ${argc} -gt 0 ] && [[ "${argv[0]}" =~ ^[0-9]+$ ]]; then
+        amount=${argv[@]:0:1}
     fi
-    local -a args=()
+    local -a tail_call=("$(builtin type -t -P tail)")
     if [ ${amount} -gt 0 ]; then
-        args=("-${amount}f")
+        tail_call+=("-${amount}f")
     else
-        args=("-f")
+        tail_call+=("-f")
     fi
-    local regexp_exclusions="$(rot13 <<<'/Gq6JSbNNNGz1eETOZN+BvROStNNNNNNNNNNNATiA4xONQypXTMlo21oJmcmpTSwMGcqKIjeJmNgBHRgEzRgMy1pX1k8GyuRG01OFH5psT9hoUypsR5CERSHDIjcNNNNF4rRV6df9+ZNNIb6E9arcu+2830ONNNNNNEMJt==' | base64 -d | unxz)"
-    tail ${args[@]} "${dnsmasq_log_path}" | grep -v "${regexp_exclusions}"
+    tail_call+=("${dnsmasq_log_path}")
+    local -- regexp_exclusions='(from[[:space:]]+[0-9A-Fa-f]+|NXDOMAIN|only|NODATA)'
+    ${tail_call[@]} | grep -v -E  "${regexp_exclusions}"
 }
 logs_help() {
     1>&2 echo -e "\x1b[1;38;5;242m$(basename $0)\x1b[1;38;5;247m logs \x1b[1;38;5;241m[#log lines]\x1b[0m"
 }
 
 refresh() {
-    2>/dev/random killall -HUP mDNSResponder
+    local -a argv=($@)
+    local -i argc=${#argv[@]}
+    1>/dev/random 2>/dev/random killall -HUP mDNSResponder
     dscacheutil -flushcache
-    2>/dev/random killall -HUP mDNSResponder
+    1>/dev/random 2>/dev/random killall -HUP mDNSResponder
     g p -S 1 -qr mDNSResponder -k
     2>/dev/random killall -HUP mDNSResponder
-    if [ -n "$1" ] && [ "$(($1 + 0))" -gt 0 ]; then
-        logs "${1}"
+    if [ ${argc} -gt 0 ]; then
+        logs ${argv[@]}
     fi
 }
 refresh_help() {
@@ -245,10 +303,18 @@ cf_prettified_json() {
 cfquery() {
     local -- response=""
     local -- filtered=""
-    local -- stderr=$(mktemp)
     local -- jq_args=('-M' '-r' '.Answer[].data')
 
-    response="$(cf_prettified_json "${@}")"
+    name=$(sed 's/^\(https\?:\/\/\)\?\([^\/]\+\)\([\/].*\)\?$/\2/g' <<< "${@}")
+
+    slug=cfquery/$(slugify-string "${name}")
+    response="$(cf_prettified_json "${name}")"
+
+    json_path="${function_log_dir}/${slug}.${now}.json"
+    log_path="${function_log_dir}/${slug}.${now}.log"
+    echo "${response}" > "${json_path}"
+    echo "jq ${jq_args[@]} <<< \"${response}\"" > "${log_path}"
+
     if ! filtered=$(2>${stderr} jq ${jq_args[@]} <<< "${response}"); then
         code=$?
         1>&2 echo -e "command failed: jq ${jq_args[@]} with input=${response@Q}"
@@ -256,23 +322,163 @@ cfquery() {
         1>&2 cat "${stderr}"
         exit $${code}
     else
-        if ! rg '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+' <<< "${filtered}"; then
-            exit $?
-        fi
+        echo -e "${name}"
+        echo -e "${filtered}"
+        # if ! rg '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+' <<< "${filtered}"; then
+        #     exit $?
+        # fi
     fi
 
 }
-wl() {
+wl_content() {
     name="$1"
     if [ -z "$name" ]; then
         exit 11
     fi
     name=$(sed 's/^\(https\?:\/\/\)\?\([^\/]\+\)\([\/].*\)\?$/\2/g' <<< "${name}")
-    data=$(cfquery "$name")
-    for row in ${data}; do
-        echo -e "\n# <$name $(date +%s)>\naddress=/$name/$row\n# </$name $(date +%Y%m%d)>" >>/opt/homebrew/etc/dnsmasq.07e80a212e0704.conf
+    slug=wl/$(slugify-string "${name}")
+    local -a ipv4_addresses=()
+    local -a data=()
+    export IFS=$'\n'
+    ipv4_addresses=($(cfquery "$name" | grep -E '[0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}'))
+    ts=$(gdate --iso-8601=seconds --date=@${now})
+    data=($(printf "address=/${name}/%s # ${ts}\n" ${ipv4_addresses[@]}))
+    log_path="${function_log_dir}/${slug}.${now}.log"
+
+    echo -e "\n#\n# <$name st ${ts}>\n"
+    printf '%s\n' ${data[@]}
+    echo -e "\n# </$name st ${ts}>\n"
+}
+
+git_command_at_path() {
+    local -- stderr=$(mktemp)
+    local -a argv=($@)
+    local -i argc=${#argv[@]}
+    local -- path=""
+    local -- git_command=""
+    local -- git_repo_path=""
+    local -a git_args=()
+    # 1>&2 echo -e "\x1b[1;38;5;220m${FUNCNAME} ${argv[@]}\x1b[0m"
+    # 1>&2 echo -e "\x1b[1;38;5;231m${argv[@]@A}\x1b[0m"
+    local -i index=0
+    local -i code=0
+    for index in ${!argv[@]}; do
+        current=$(( index + 1 ))
+        arg=${argv[$index]}
+        err_prefix="[${current}/${argc}]"
+        case "${index}" in
+            0)
+                path="${arg}"
+                if [ ! -d "${path}" ]; then
+                    1>&2 echo -e "${err_prefix}${FUNCNAME[0]} invalid <PATH> argument (not a directory): ${path@Q}"
+                    return 1
+                fi
+                if ! git_repo_path=$(cd "${path}" && 2>${stderr} git rev-parse --show-toplevel); then
+                    code=$?
+                    1>&2 echo -e "${err_prefix}${FUNCNAME[0]} invalid <PATH> argument (not in a git repo): ${path@Q}"
+                    1>&2 echo -e "${err_prefix}$(cat "${stderr}")"
+                    return ${code}
+                fi
+                git_prefix_path=$(cd "${path}" && git rev-parse --show-prefix)
+                if [ -n "${git_prefix_path}" ]; then
+                    path="${git_prefix_path}"
+                fi
+                ;;
+            1)
+                git_command="${arg}"
+                ;;
+            *)
+                git_args+=("${arg}")
+            ;;
+        esac
     done
-    echo $data
+    if [ -z "${path}" ]; then
+        1>&2 echo -e "${FUNCNAME[0]} missing argument <PATH>"
+        return 1
+    elif [ -z "${git_command}" ]; then
+        1>&2 echo -e "${FUNCNAME[0]} missing argument <GIT_COMMAND>"
+        return 1
+    fi
+    local -- stdout=$(mktemp)
+    local -a full_cmd=(git ${git_command} ${git_args[@]})
+    if ! (cd ${path} && 2>${stderr} 1>${stdout} ${full_cmd[@]}); then
+        code=$?
+        if [ ${code} -ne 0 ]; then
+            1>&2 echo -e "running command \`${full_cmd[@]}\' in path ${path@Q} failed exit code ${code}"
+            1>&2 echo -e "$(cat ${stderr})"
+            cat ${stdout}
+            return ${code}
+        fi
+    fi
+    cat ${stdout}
+}
+conf_file_changed() {
+    if ! changed=$(git_command_at_path "${conf_parent_path}" status --porcelain | awk '{ print $NF }' | grep -E "^${conf_filename//./[.]}\$"); then
+        return $?
+    fi
+}
+commit_conf_file() {
+    local -a prefix=()
+    local -- subject="${@}"
+    local -- message=""
+    local -a parts=()
+    local -- stderr=$(mktemp)
+    if [ -z "${subject}"  ]; then
+        prefix=(
+            "${script_name}"
+            ${main_argv[@]}
+        )
+        parts=(
+            ${prefix[@]}
+            "saves"
+            "${conf_filename}"
+        )
+    else
+        parts=(
+            "${subject}"
+        )
+    fi
+    message=$(printf "%s " ${parts[@]} | sed -E 's/\s+$//g')
+    log_path="${function_log_dir}/${FUNCNAME[0]}.${now}.log"
+    stderr="${function_log_dir}/${FUNCNAME[0]}.${now}.stderr.log"
+
+    if ! output=$(git_command_at_path "${conf_parent_path}" commit ${conf_filename} -m "${message}"); then
+        return $?
+    fi
+}
+wl() {
+    local -a wl_argv=($@)
+    local -i wl_argc=${#wl_argv[@]}
+    local -i index=0
+    local -i current=0
+    local -- arg=""
+
+    if [ ${wl_argc} -eq 0 ]; then
+        1>&2 echo -e "${script_name} ${FUNCNAME[0]}" "missing argument <NAME OR URL>"
+        exit 1
+    fi
+
+    name=$(extract_domain "${wl_argv[@]:0:1}")
+    local -- content=""
+    export IFS=$'\n'
+
+    if conf_file_changed; then
+        if ! commit_conf_file "save conf prior to running \"dns-server wl ${name@Q}\""; then
+            code=$?
+            1>&2 echo "failed (${code}) to commit ${dnsmasq_conf_path}"
+        fi
+    fi
+
+    sed -E "/address=\/${name//./[.]}\//d" -i ${dnsmasq_conf_path}
+    sed -E "/^\s*[#]\s*[<][\/]?${name//./[.]}/d" -i ${dnsmasq_conf_path}
+    wl_content "${name}" | sed -E '/^\s*$/d' | sed -E 's/^[#]$/\n/g' >>${dnsmasq_conf_path}
+    if conf_file_changed; then
+        if ! commit_conf_file "save conf after running \"dns-server wl ${name@Q}\""; then
+            code=$?
+            1>&2 echo "failed (${code}) to commit ${dnsmasq_conf_path}"
+        fi
+    fi
+
     restart
 }
 
@@ -282,7 +488,7 @@ block() {
         exit 11
     fi
     row=23.50.77.69
-    echo -e "\n# <block $name $(date +%s)>\naddress=/$name/$row\n# </block $name $(date +%Y%m%d)>" >>/opt/homebrew/etc/dnsmasq.07e80a212e0704.conf
+    echo -e "\n# <block $name ${now}>\naddress=/$name/$row\n# </block $name $(gdate +%Y%m%d --date=@${now})>" >>${dnsmasq_conf_path}
     echo "blocked: ${name}"
     restart
 }
diff --git a/gabrielfalcao/opt/libexec/emacs b/gabrielfalcao/opt/libexec/emacs
--- a/gabrielfalcao/opt/libexec/emacs
+++ b/gabrielfalcao/opt/libexec/emacs
@@ -1,25 +1,133 @@
 #!/usr/bin/env bash
+. ~/.shell.d/x.d/workbench.sh
 
-socket="$HOME/.emacs.d/socket/server"
+workbench_refresh || true
 
-working_path="$(pwd)"
-log_timestamp="$(date +"%Y%m%d-%H%M%S")"
-stdout_log_path="$HOME/opt/var/log/emacs.out.${log_timestamp}.log"
-stderr_log_path="$HOME/opt/var/log/emacs.err.${log_timestamp}.log"
-exec="/Applications/Emacs.app/Contents/MacOS/Emacs-arm64-11"
-homebrew_bin="/opt/homebrew/bin/emacs"
+unset IFS
+declare -- emacs_d_path="$HOME/.emacs.d"
+declare -- emacs_d_socket_dir="${emacs_d_path}/socket"
+declare -- socket="${emacs_d_socket_dir}/server"
+declare -- emacs_d_boot_pidfile="${emacs_d_path}/boot.info"
+declare -a pidfile_data=()
+
+declare -- working_path="$(pwd)"
+declare -- log_timestamp="$(date +"%Y%m%d-%H%M%S")"
+declare -- stdout_log_path="$HOME/opt/var/log/emacs.out.${log_timestamp}.log"
+declare -- stderr_log_path="$HOME/opt/var/log/emacs.err.${log_timestamp}.log"
+declare -- exec="/Applications/Emacs.app/Contents/MacOS/Emacs-arm64-11"
+declare -- homebrew_bin="/opt/homebrew/bin/emacs"
 declare -a exec_args=()
+export IFS=$'\n'
+declare -a lsof_lines_socket_server_matching_emacs_command=()
+declare -a socket_pids=()
+
+require_socket_file_bound_to_any_pid() {
+    if [ ! -S "${socket}" ]; then
+        1>&2 echo -e "socket file does not exist at expected location \x1b[1;38;5;220m${socket}\x1b[0m"
+        exit 1
+    fi
+
+    if ! lsof_lines_socket_server_matching_emacs_command=($(lsof "${socket}" | grep -Ei '^emacs')); then
+        1>&2 echo -e "no \x1b[3;38;5;154memacs\x1b[0m process bound to socket file \x1b[1;38;5;220m${socket}\x1b[0m"
+        code=$?
+        exit ${code}
+    fi
+    if [ ${#lsof_lines_socket_server_matching_emacs_command[@]} -eq 0 ]; then
+        1>&2 echo -e "no \x1b[3;38;5;154memacs\x1b[0m process bound to socket file \x1b[1;38;5;220m${socket}\x1b[0m"
+        exit $((404 % 255))
+    fi
+    if ! socket_pids=($(printf '%s\n' "${lsof_lines_socket_server_matching_emacs_command[@]}" | awk '{ print $2 }')); then
+        1>&2 echo -e "no pids matching \x1b[3;38;5;154memacs\x1b[0m processed bound to socket file \x1b[1;38;5;220m${socket}\x1b[0m"
+        1>&2 printf '%s\n' "${lsof_lines_socket_server_matching_emacs_command[@]}"
+        code=$?
+        exit ${code}
+    fi
+    if [ ${#socket_pids[@]} -eq 0 ]; then
+        1>&2 echo -e "no pids matching \x1b[3;38;5;154memacs\x1b[0m processed bound to socket file \x1b[1;38;5;220m${socket}\x1b[0m"
+        exit $((404 % 255))
+    fi
+}
+
+update_pidfile() {
+    local -a up_argv=($@)
+    local -i up_argc=${!up_argv[@]}
+    local -i index=0
+    local -i current=0
+    local -- arg=""
+    local -i pid=0
+    local -A pids=()
+    local -i now=$(date +%s)
+    for index in ${!up_argv[@]}; do
+        arg="${up_argv[$index]}"
+        if pid=$(awk '{ if ($pos ~ /^[0-9]+$/) { print $0; } else { exit 1; }}' <<<"${arg}") 2>/dev/random; then
+            pids+=(["${index}"]="${pid}")
+        fi
+    done
+    ps_regex="^\s*($(printf '%s|' ${pids[@]} | sed -E 's/[|]$//g'))\s+(.+)\s*\$"
+    set -x
+    local -a active_pids=($(ps axo pid,args | grep -E "${ps_regex}" | awk '{print $2}'))
+    set +x
+
+    local pidcount=${#active_pids[@]}
+    if [ ${pidcount} -gt 1 ]; then
+        1>&2 echo "[update_pidfile]" "ignoring extra pids: ${pids[@]:1}"
+        for val in ${active_pids[@]}; do
+            pid=${val}
+        done
+    fi
+    local pidfile_contents="${pid}:${now}"
+    if [ ${pid} -gt 0 ]; then
+        echo "${pidfile_contents}" >${emacs_d_boot_pidfile}
+    else
+        return 1
+    fi
+}
+read_pidfile() {
+    if [ ! -f "${emacs_d_boot_pidfile}" ] || [ ! -s "${emacs_d_boot_pidfile}" ]; then
+        update_pidfile
+        return 1
+    fi
+    regex='^([0-9]+):([0-9]+)$'
+    sed_command="/${regex}/{s/${regex}/\n\1\n\2\n/gp};t success q1;:success q0"
+    local -a pidfile_data=()
+    export IFS=$'\n'
+    pidfile_data=($(sed -n -E "${sed_command}" "${emacs_d_boot_pidfile}"))
+    if [ ${pidfile_data} -ne 2 ]; then
+        1>&2 echo "failed to read pidfile data from ${emacs_d_boot_pidfile@Q}, instead of 2 fields got $(printf '%sm ' ${pidfile_data[@]})"
+        return 1
+    else
+        printf '%s\n' ${pidfile_data[@]}
+    fi
+}
+
+get_emacs_pids() {
+    ps aux | grep -v grep | grep -E 'Emacs[.]app' | awk '{ print $2 }'
+}
+kill_emacs() {
+    local -a pidstokill=()
+    pidstokill=( $(get_emacs_pids) )
+    if [ ${#pidstokill[@]} -gt 0 ]; then
+        kill -9 ${pidstokill[@]}
+    fi
+}
 
 client() {
-    2>/dev/random /Applications/Emacs.app/Contents/MacOS/bin/emacsclient $*
+    local -a argv=($@)
+    local -i argc=${#argv[@]}
+    require_socket_file_bound_to_any_pid
+    2>/dev/random /Applications/Emacs.app/Contents/MacOS/bin/emacsclient --socket-name "${socket}" ${argv[@]}
 }
 
 if [ "$0" == "${BASH_SOURCE[0]}" ]; then
-    delete_socket=
-    kill=
+    declare -- delete_socket=
+    declare -- kill=
 
     for arg in $@; do
         case "$arg" in
+            "-p")
+                echo "${exec}"
+                exit 0
+            ;;
             "-f")
                 delete_socket=true
                 kill=true
@@ -32,7 +140,7 @@ if [ "$0" == "${BASH_SOURCE[0]}" ]; then
                 ;;
             "-nw")
                 export EMACS_NO_SERVER=true
-                exec_args+=("${arg}")
+                declare -- exec_args+=("${arg}")
                 if [ ! -e "${homebrew_bin}" ]; then
                     1>&2 echo "${homebrew_bin@Q} does not exist"
                     exit 1
@@ -49,16 +157,16 @@ if [ "$0" == "${BASH_SOURCE[0]}" ]; then
                     1>&2 echo "${homebrew_bin@Q} is not executable"
                     exit 1
                 fi
-                exec=/opt/homebrew/bin/emacs
+                declare -- exec=/opt/homebrew/bin/emacs
                 ;;
             *)
-                exec_args+=("${arg}")
+                declare -- exec_args+=("${arg}")
                 ;;
         esac
     done
 
     if [ "$kill" == "true" ]; then
-        2>/dev/random 1>/dev/random g p -r Emacs -k
+        kill_emacs
     fi
     if [ "$delete_socket" == "true" ]; then
         2>/dev/random 1>/dev/random rm -f "$socket"
diff --git a/gabrielfalcao/opt/libexec/figlet-showcase b/gabrielfalcao/opt/libexec/figlet-showcase
--- a/gabrielfalcao/opt/libexec/figlet-showcase
+++ b/gabrielfalcao/opt/libexec/figlet-showcase
@@ -1,12 +1,253 @@
+#!/usr/bin/env bash
+
+export IFS=$'\n'
+set -umeTE
+set +f
+set -o pipefail
+unset IFS
+
+script_name="$(basename "${BASH_SOURCE[0]}")"
+script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
+this_script_path="${script_path}/${script_name}"
+
+
+declare -- default_figlet_installation_path="/usr/share/figlet"
+declare -- figlet_installation_path="${default_figlet_installation_path}"
+declare -- figlet_fonts_path=""
+declare -- default_figlet_fonts_path=""
+
+declare -a argv=($@)
+declare -i argc=${#argv[@]}
+declare -- git_repo_path=""
+declare -i exit_code=0
+declare -- curdir=$(pwd)
+declare -a font_files=()
+declare -a font_directories=()
+declare -- TEXT="Hello World"
+
+
+declare -- error_prefix_color_rgb="239;41;41"
+declare -- error_color_rgb="204;0;0"
+
+declare -- achtung_prefix_color_rgb="245;121;0"
+declare -- achtung_color_rgb="206;92;0"
+
+declare -- warn_prefix_color_rgb="252;233;79"
+declare -- warn_color_rgb="237;212;00"
+
+declare -- info_prefix_color_rgb="52;101;164"
+declare -- info_color_rgb="114;159;207;"
+
+declare -- msg_prefix_color_rgb="186;189;182"
+declare -- msg_color_rgb="136;138;133"
+
+declare -- display_prefix_color_rgb="238;238;236"
+declare -- display_color_rgb="211;215;207"
+
+declare -- debug_prefix_color_rgb="138;226;52"
+declare -- debug_color_rgb="115;210;22"
+
+on_exit() {
+    2>/dev/random 1>/dev/random stty sane
+}
+on_ctrlc() {
+    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
+    exit 1
+}
+trap on_exit exit
+trap on_ctrlc hup
+trap on_ctrlc int
+trap on_ctrlc bus
+trap on_ctrlc segv
+trap on_ctrlc sys
+
+repl() {
+    local -a stty_args=()
+    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
+    2>/dev/random 1>/dev/random stty ${stty_args[@]}
+}
+usage() {
+    repl no echo
+    1>&2 echo -e "$(basename $0) <ARGUMENT>"
+    repl sane
+}
+exit_error() {
+    error "${@}"
+    exit 1
+}
+
+achtung_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
+}
+achtung() {
+    local -- linenum="${BASH_LINENO[0]}"
+    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
+}
+warn_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
+}
+warn() {
+    local -- linenum="${BASH_LINENO[0]}"
+    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
+}
+error() {
+    local -- linenum="${BASH_LINENO[0]}"
+    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
+}
+error_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
+}
+info() {
+    local -- linenum="${BASH_LINENO[0]}"
+    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
+}
+info_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
+}
+msg() {
+    local -- linenum="${BASH_LINENO[0]}"
+    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
+}
+msg_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
+}
+display() {
+    local -- linenum="${BASH_LINENO[0]}"
+    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
+}
+display_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
+}
+debug_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
+}
+debug() {
+    local -- linenum="${BASH_LINENO[0]}"
+    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
+}
+trace() {
+    if [ -z "${BASH_TRACE}" ] && [ "${BASH_LOGLEVEL}" != "trace" ]; then
+        return 0
+    fi
+
+    local -- linenum="${BASH_LINENO[0]}"
+    local -- funcname="${FUNCNAME[1]}"
+    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
+}
+
+process_argv() {
+    if ! default_figlet_fonts_path=$(figlet -I2); then
+        exit_code=$?
+        error_prefixed "[system error]" "command \x60figlet -I2\x60 failed with exit code ${exit_code} therefore could not determine figlet's default directory. Perhaps figlet is not installed?!?"
+        exit ${exit_code}
+    fi
+
+    if [ ! -d "${figlet_installation_path}" ]; then
+        if ! figlet_installation_path=$(brew --prefix figlet); then
+            exit_code=$?
+            error_prefixed "[system error]" "figlet is not installed in the default path ${default_figlet_installation_path@Q} and command \x60brew --prefix figlet\x60 failed with exit code ${exit_code}"
+            exit ${exit_code}
+        fi
+    fi
+
+    repl no echo
+    local -i current=0
+    local -i index=0
+    local -- arg=""
+    local -i skip_next=0
+    local -- next_arg=""
+    for index in ${!argv[@]}; do
+        if (( $skip_next )); then
+            skip_next=0
+            continue
+        fi
+        next_arg=""
+        current=$(($index + 1))
+        arg="${argv[$index]}"
+        if [[ -v argv[$current] ]]; then
+            next_arg="${argv[$current]}"
+        fi
+        case "${arg}" in
+            *.flf|*.flf2|*.ylf|*.tlf2)
+                font_files+=("${arg}")
+                ;;
+            -f)
+                if [ -n "${next_arg}" ]; then
+                    font_files+=("${next_arg}")
+                    skip_next=1
+                else
+                    error_prefixed "[argument error]" "missing filename argument following argument ${current} of ${argc}: ${arg@Q}"
+                    exit 1
+                fi
+                ;;
+            -f=*)
+                next_arg="${arg#-f=}"
+                if [ -n "${next_arg}" ]; then
+                    font_files+=("${next_arg}")
+                else
+                    error_prefixed "[argument error]" "missing filename argument after \042=\042 ${current} of ${argc}: ${arg@Q}"
+                    exit 1
+                fi
+            -d)
+                if [ -n "${next_arg}" ]; then
+                    font_directories+=("${next_arg}")
+                    skip_next=1
+                else
+                    error_prefixed "[argument error]" "missing filename argument following argument ${current} of ${argc}: ${arg@Q}"
+                    exit 1
+                fi
+                ;;
+            -d=*)
+                next_arg="${arg#-d=}"
+                if [ -n "${next_arg}" ]; then
+                    font_directories+=("${next_arg}")
+                else
+                    error_prefixed "[argument error]" "missing filename argument after \042=\042 ${current} of ${argc}: ${arg@Q}"
+                    exit 1
+                fi
+
+                ;;
+
+    done
+    repl sane
+}
+
+main() {
+    info_prefixed "[${script_name}]" "main"
+}
+
+if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
+    if process_argv ${argv[@]}; then
+        main
+    fi
+else
+    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
+fi
+repl sane
 #!/bin/bash
 
-TEXT="$@"
-
-if [ -z "$TEXT" ]; then
-    TEXT="Hello World"
-fi
-
-function display()  {
+function display() {
     local -r lpath="$(brew --prefix figlet)/share/figlet/fonts"
     for font in $(find "$lpath" -name "*.flf" -not -path '*C64*'); do
         directory=$(dirname $font)
@@ -21,10 +262,9 @@ function display()  {
         printf "\n\n"
         if [ "$?" != "0" ]; then
             exit 1
-        fi;
+        fi
     done
 }
-
 
 display | bat --style grid
 reset
diff --git a/gabrielfalcao/opt/libexec/unfreeze b/gabrielfalcao/opt/libexec/unfreeze
--- a/gabrielfalcao/opt/libexec/unfreeze
+++ b/gabrielfalcao/opt/libexec/unfreeze
@@ -1,8 +1,246 @@
 #!/usr/bin/env bash
 
-set -e
+export IFS=$'\n'
+set -umeTE
+set +f
 set -o pipefail
-set -u
+unset IFS
 
+script_name="$(basename "${BASH_SOURCE[0]}")"
+script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
+this_script_path="${script_path}/${script_name}"
 
-sudo g p -r '(audio|coreduet|spotlight|chrome)' -k
+declare -- actual_user="${USER}"
+if [ "${USER}" == "root" ]; then
+    actual_user="$(/usr/bin/id -un)"
+fi
+
+if [ "${actual_user}" != "root" ]; then
+    # 1>&2 echo -e "$(basename ${script_name}) must run as root, not ${actual_user}"
+    # exit 1
+    sudo ${this_script_path}
+    exit $?
+fi
+
+declare -a command_or_args_regexps=(
+    '(audio|coreduet|spotlight|chrome|google|chrome|coreduetd|coreaudiod|logd|biomed|main|/Frameworks/com[.]apple|aned|launchd|agent|continuity|browser|ws.*thread|thermal|monitor|mdns|control|center|airport)'
+)
+declare -a possibly_duped_pids=()
+declare -a possibly_duped_parent_pids=()
+declare -A rogue_pids=()
+declare -A rogue_parent_pids=()
+declare -i pid=-1
+declare -i parent_pid=-1
+declare -i cmd_and_args=-1
+
+export IFS=$'\n'
+declare -a ps_axo_output=()
+declare -- stderr=$(mktemp)
+declare -a cmdargs_ppid_pid_triple=()
+declare -i triple_len=-1
+declare -i triple_len=-1
+
+declare -a argv=($@)
+declare -i argc=${#argv[@]}
+declare -- git_repo_path=""
+declare -i exit_code=0
+declare -- curdir=$(pwd)
+
+declare -- error_prefix_color_rgb="239;41;41"
+declare -- error_color_rgb="204;0;0"
+
+declare -- achtung_prefix_color_rgb="245;121;0"
+declare -- achtung_color_rgb="206;92;0"
+
+declare -- warn_prefix_color_rgb="252;233;79"
+declare -- warn_color_rgb="237;212;00"
+
+declare -- info_prefix_color_rgb="52;101;164"
+declare -- info_color_rgb="114;159;207;"
+
+declare -- msg_prefix_color_rgb="186;189;182"
+declare -- msg_color_rgb="136;138;133"
+
+declare -- display_prefix_color_rgb="238;238;236"
+declare -- display_color_rgb="211;215;207"
+
+declare -- debug_prefix_color_rgb="138;226;52"
+declare -- debug_color_rgb="115;210;22"
+
+on_exit() {
+    2>/dev/random 1>/dev/random stty sane
+}
+on_ctrlc() {
+    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
+    exit 1
+}
+trap on_exit exit
+trap on_ctrlc hup
+trap on_ctrlc int
+trap on_ctrlc bus
+trap on_ctrlc segv
+trap on_ctrlc sys
+
+repl() {
+    local -a stty_args=()
+    case "$1" in -*no*stdin | no*stdin | -*no*echo | no*echo | capture) args+=('-echo') ;; *) args+=('sane') ;; esac
+    2>/dev/random 1>/dev/random stty ${stty_args[@]}
+}
+usage() {
+    repl no echo
+    1>&2 echo -e "$(basename $0) <ARGUMENT>"
+    repl sane
+}
+exit_error() {
+    error "${@}"
+    exit 1
+}
+
+achtung_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${achtung_prefix_color_rgb}m${prefix}\x1b[1;38;2;${achtung_color_rgb}m ${message}\x1b[0m"
+}
+achtung() {
+    local -- linenum="${BASH_LINENO[0]}"
+    achtung_prefixed "[achtung]  [${script_name}:${linenum}]" "${@}"
+}
+warn_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
+}
+warn() {
+    local -- linenum="${BASH_LINENO[0]}"
+    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
+}
+error() {
+    local -- linenum="${BASH_LINENO[0]}"
+    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
+}
+error_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
+}
+info() {
+    local -- linenum="${BASH_LINENO[0]}"
+    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
+}
+info_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
+}
+msg() {
+    local -- linenum="${BASH_LINENO[0]}"
+    msg_prefixed "[msg]  [${script_name}:${linenum}]" "${@}"
+}
+msg_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${msg_prefix_color_rgb}m${prefix}\x1b[1;38;2;${msg_color_rgb}m ${message}\x1b[0m"
+}
+display() {
+    local -- linenum="${BASH_LINENO[0]}"
+    display_prefixed "[display]  [${script_name}:${linenum}]" "${@}"
+}
+display_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${display_prefix_color_rgb}m${prefix}\x1b[1;38;2;${display_color_rgb}m ${message}\x1b[0m"
+}
+debug_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
+}
+debug() {
+    local -- linenum="${BASH_LINENO[0]}"
+    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
+}
+trace() {
+    if [ -z "${BASH_TRACE}" ] && [ "${BASH_LOGLEVEL}" != "trace" ]; then
+        return 0
+    fi
+
+    local -- linenum="${BASH_LINENO[0]}"
+    local -- funcname="${FUNCNAME[1]}"
+    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
+}
+
+process_argv() {
+    if ! git_repo_path=$(git rev-parse --show-toplevel); then
+        error_prefixed "[${script_name} error]" "${curdir@Q} is not a git repo"
+        exit 1
+    fi
+
+    repl no echo
+    local -i current=0
+    local -i index=0
+    local -- arg=""
+
+    for index in ${!argv[@]}; do
+        current=$(($index + 1))
+        arg="${argv[$index]}"
+    done
+
+    local -- ps_command="ps axo command,args,ppid,pid"
+    if ! ps_axo_output=($(2>${stderr} ps axo command,args,ppid,pid)); then
+        warn_prefixed "failed to run ${ps_command}" "$(cat ${stderr})"
+        exit 1
+    fi
+
+    repl sane
+}
+
+main() {
+    local -i line_index=0
+    local -i current_line_no=0
+    for line_index in ${!ps_axo_output[@]}; do
+        current_line_no=$(( $line_index + 1 ))
+        line=${ps_axo_output[$line_index]}
+        for regexp in ${command_or_args_regexps}; do
+            rogue_pids=$(ps aux | grep -i -E "${regexp}" | grep -v grep | awk '{ print $2 }')
+            for pid in ${rogue_pids}; do
+                ps aux | grep -E "^\s*[^[:space:]]+\s+\b${pid}\b"
+                kill -9 ${pid} || true
+            done
+            continue
+
+            if ! cmdargs_ppid_pid_triple=($(gawk "\$1 ~ /${regexp}/{ NFM1=(NF - 1); LNPF=(NFM1-1) for (cmda=1;cmda<=LNPF;cmda++) { suffix=' '; if (cmda == LNPF) {suffix='\n';} printf( '%s%s', \$cmda, suffix); }; printf( '\n%s\n%s\n', \$NFM1, \$NF) }" <<<"${line}")); then
+                # 1>&2 echo -e "[warn]" "skipping non-matched line: ${line@Q}"
+                continue
+            fi
+            triple_len=${#cmdargs_ppid_pid_triple[@]}
+            if [ ${triple_len} -ne 3 ]; then
+                warn_prefixed "[warn]" "cmdargs_ppid_pid_triple should have 2 items but got ${triple_len}: ${cmdargs_ppid_pid_triple[@]@Q}"
+                continue
+            fi
+            cmd_and_args=${cmdargs_ppid_pid_triple[0]}
+            parent_pid=${cmdargs_ppid_pid_triple[1]}
+            pid=${cmdargs_ppid_pid_triple[2]}
+            rogue_parent_pids+=(["${parent_pid}"]="${cmd_and_args}")
+            rogue_pids+=(["${pid}"]="${cmd_and_args}")
+        done
+    done
+
+    echo -e "${rogue_pids[@]@A}"
+    echo -e "${rogue_parent_pids[@]@A}"
+}
+
+if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
+    if process_argv ${argv[@]}; then
+        main
+    fi
+else
+    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
+fi
+repl sane
diff --git a/gabrielfalcao/opt/libexec/wifi b/gabrielfalcao/opt/libexec/wifi
--- a/gabrielfalcao/opt/libexec/wifi
+++ b/gabrielfalcao/opt/libexec/wifi
@@ -1,6 +1,194 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2004,SC2206,SC2068,SC2086
+#!/opt/homebrew/bin/bash
 
+. ~/.shell.d/x.d/paths.sh
+
+export IFS=$'\n'
+set -ueTE
+set +f
+set -o pipefail
+unset IFS
+
+script_name="$(basename "${BASH_SOURCE[0]}")"
+script_path="$(2>/dev/random 1>/dev/random cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
+this_script_path="${script_path}/${script_name}"
+declare -a argv=($@)
+declare -i argc=${#argv[@]}
+declare -a dns_servers_ipv4=()
+if [[ -v DNS_SERVERS ]]; then
+    unset IFS
+    dns_servers_ipv4+=($(printf '%s\n' ${DNS_SERVERS[@]}))
+    export IFS=$'\n'
+fi
+
+declare -- action=""
+declare -a action_args=()
+declare -- backup_path="$HOME/*scratch*/Data/Backups/$(slugify-string '/Library/Preferences/SystemConfiguration')"
+declare -a filenames=("com.apple.airport.preferences.plist" "com.apple.wifi.message-tracer.plist" "com.apple.network.identification.plist" "com.apple.network.eapolclient.configuration.plist" "NetworkInterfaces.plist" "preferences.plist")
+declare -a backed_up=()
+declare -a not_found=()
+declare -- diagnostic_path="$HOME/workbench/$(date +'%Y-%M-%d')/wifi-diagnostic"
+declare -a known_opts=(
+    "on"
+    "up"
+    "down"
+    "off"
+    "reboot"
+    "restart"
+    "-h"
+    "--help"
+)
+
+export IFS=$'\n'
+
+declare -- error_prefix_color_rgb="255;0;66"
+declare -- error_color_rgb="255;62;92"
+declare -- warn_prefix_color_rgb="255;106;50"
+declare -- warn_color_rgb="255;161;50"
+declare -- info_prefix_color_rgb="0;66;255"
+declare -- info_color_rgb="62;92;255"
+declare -- debug_prefix_color_rgb="50;255;106"
+declare -- debug_color_rgb="50;255;161"
+
+on_exit() {
+    2>/dev/random 1>/dev/random stty sane
+}
+on_ctrlc() {
+    1>&2 echo -e "\x1b[1;38;2;${error_color_rgb}m\rAborted with Ctrl-C\x1b[0m"
+    exit 1
+}
+trap on_exit exit
+trap on_ctrlc hup
+trap on_ctrlc int
+trap on_ctrlc bus
+trap on_ctrlc segv
+trap on_ctrlc sys
+
+warn_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${warn_prefix_color_rgb}m${prefix}\x1b[1;38;2;${warn_color_rgb}m ${message}\x1b[0m"
+}
+warn() {
+    local -- linenum="${BASH_LINENO[0]}"
+    warn_prefixed "[warn]  [${script_name}:${linenum}]" "${@}"
+}
+error() {
+    local -- linenum="${BASH_LINENO[0]}"
+    error_prefixed "[error] [${script_name}:${linenum}]" "${@}"
+}
+error_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${error_prefix_color_rgb}m${prefix}\x1b[1;38;2;${error_color_rgb}m ${message}\x1b[0m"
+}
+info() {
+    local -- linenum="${BASH_LINENO[0]}"
+    info_prefixed "[info]  [${script_name}:${linenum}]" "${@}"
+}
+info_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${info_prefix_color_rgb}m${prefix}\x1b[1;38;2;${info_color_rgb}m ${message}\x1b[0m"
+}
+debug_prefixed() {
+    local -- prefix="$1"
+    shift
+    local -- message="$@"
+    1>&2 echo -e "\x1b[1;38;2;${debug_prefix_color_rgb}m${prefix}\x1b[1;38;2;${debug_color_rgb}m ${message}\x1b[0m"
+}
+debug() {
+    local -- linenum="${BASH_LINENO[0]}"
+    debug_prefixed "[debug] [${script_name}:${linenum}]" "${@}"
+}
+trace() {
+    if [ -z "${BASH_TRACE}" ] && [ "${BASH_LOGLEVEL}" != "trace" ]; then
+        return 0
+    fi
+
+    local -- linenum="${BASH_LINENO[0]}"
+    local -- funcname="${FUNCNAME[1]}"
+    debug_prefixed "[${FUNCNAME[0]} ${script_name}::${funcname}:${linenum}]" "${@}"
+}
+
+unset TZ
+2>/dev/random mkdir -p "${diagnostic_path}"
+
+wifi_enable_all_logs() {
+    sudo wdutil log +dhcp +od +dns +eapol +wifi
+}
+
+wifi_diagnose() {
+    local -i started=0
+    local -i finished=0
+    local -- stderr=$(mktemp)
+    local -- stdout=$(mktemp)
+    local -- log_filename=""
+    local -i code=0
+    set -o pipefail
+    started=$(date +%s)
+
+    warn_prefixed 'wifi_diagnose' "2>${stderr} sudo wdutil diagnose -f \"${diagnostic_path}\" 1>${stdout}"
+    if ! 2>${stderr} sudo wdutil diagnose -f "${diagnostic_path}" | tee ${stdout}; then
+        code=$?
+    fi
+    finished=$(date +%s)
+    elapsed=$(($finished - $started))
+    log_basename="wifi-diagnostic-$(gdate +'%Y-%m-%d_%H-%M-%S_%Z' --date=@${started})"
+    log_stderr_filename="${log_basename}.stderr.log"
+    log_stdout_filename="${log_basename}.stdout.log"
+    stderr_dest_path="${diagnostic_path}/${log_stderr_filename}"
+    stdout_dest_path="${diagnostic_path}/${log_stdout_filename}"
+    mkdir -p $(dirname "${stderr_dest_path}")
+    if cp -f "${stderr}" "${stderr_dest_path}" && cp -f "${stderr}" "${stderr_dest_path}"; then
+        1>&2 echo -e "diagnostic saved to ${stderr_dest_path@Q} and ${stdout_dest_path@Q}"
+    else
+        mv_code=$?
+        1>&2 echo -e "error ${mv_code} moving stderr and stdout logs to destination paths:"
+        1>&2 echo -e "\t${stderr@Q} to ${stderr_dest_path@Q}"
+        1>&2 echo -e "\t${stdout@Q} to ${stdout_dest_path@Q}"
+    fi
+    git add -f "${diagnostic_path}" || true
+    return ${code}
+}
+
+wifi_fix() {
+    # https://www.reddit.com/r/MacOS/comments/1ijn5n9/comment/mhpvh9u/
+
+    # Open a Finder window. Press Command + Shift + G. Type the
+    # following path into the search box:
+    # /Library/Preferences/SystemConfiguration/ Delete the following
+    # files: com.apple.airport.preferences.plist
+    # com.apple.wifi.message-tracer.plist
+    # com.apple.network.identification.plist
+    # com.apple.network.eapolclient.configuration.plist
+    # NetworkInterfaces.plist preferences.plist
+
+    # FIRST, BACKUP
+    # mkdir -p
+
+    for name in ${filenames[@]}; do
+        plist_path="/Library/Preferences/SystemConfiguration/${name}"
+        if [ -f "${plist_path}" ]; then
+            if ! sudo cp -fv "${plist_path}" "${backup_path}"; then
+                break
+            else
+                backed_up+=("${plist_path}")
+            fi
+        else
+            not_found+=("${plist_path}")
+        fi
+    done
+
+    for index in ${!backed_up[@]}; do
+        path=${backed_up[$index]}
+        sudo rm -fv "${path}"
+    done
+    setmac
+    wifi_reboot
+}
 ctrlc() {
     stty sane
     1>&2 echo -e "\rAborted with Ctrl-C"
@@ -13,20 +201,7 @@ if [ "$(whoami)" != "root" ]; then
     sudo $0 $@
     exit $?
 fi
-declare -a argv=($@)
-declare argc=${#argv}
 
-declare -a known_opts=(
-    "on"
-    "up"
-    "down"
-    "off"
-    "reboot"
-    "restart"
-    "-h"
-    "--help"
-)
-declare -a action_args=()
 
 usage() {
     stty sane
@@ -35,10 +210,7 @@ usage() {
 
 if [ ${#argv} -gt 0 ]; then
     for arg in ${argv[@]}; do
-        if [ -n "${action}" ]; then
-            action_args+=("${arg}")
-            continue
-        fi
+        arg=$(sed -E 's/(^\s*|\s*$)//g' <<<"${arg}")
         case "${arg}" in
             "--help" | "-h")
                 usage
@@ -47,20 +219,36 @@ if [ ${#argv} -gt 0 ]; then
             "up" | "on")
                 action="on"
                 ;;
+            setup*log* | log*setup | configure*log* | enable*all*log*)
+                action="enable_all_logs"
+                ;;
+            "diag" | "diagnose" | "diagnostic" | "diagnostics")
+                action="diagnose"
+                ;;
             "down" | "off")
                 action="off"
+                ;;
+            "fix")
+                action="fix"
                 ;;
             "restart" | "reboot")
                 action="reboot"
                 ;;
             *)
-                1>&2 echo -e "unknown option: ${arg@Q}"
-                1>&2 usage
-                exit 1
+                if 2>/dev/random 1>/dev/random grep -E '^([0-9]{1,3}[.])+([0-9]{1,3})' <<<"${arg}"; then
+                    dns_servers_ipv4+=("${arg}")
+                else
+                    action_args+=("${arg}")
+                fi
+                continue
                 ;;
         esac
     done
 fi
+if [ ${#dns_servers_ipv4[@]} -eq 0 ]; then
+    dns_servers_ipv4+=("127.0.0.1")
+fi
+
 
 sleep_for() {
     seconds="${1}"
@@ -68,14 +256,14 @@ sleep_for() {
         1>&2 echo -e "sleep_for - missing argument: <SECONDS>"
         exit 1
     fi
-    if ! 1>/dev/random 2>/dev/random grep '^[0-9]\+$' <<< "${seconds}"; then
+    if ! 1>/dev/random 2>/dev/random grep '^[0-9]\+$' <<<"${seconds}"; then
         1>&2 echo -e "sleep_for - invalid argument, not a number: ${seconds@Q}"
         exit 1
     fi
     1>/dev/random 2>/dev/random stty -echo || true
     echo -e "waiting ${seconds}s"
-    for int in $(seq $(( 1 + $seconds ))); do
-        delta=$(( ${seconds} - ${int} + 1 ))
+    for int in $(seq $((1 + $seconds))); do
+        delta=$((${seconds} - ${int} + 1))
         echo -e "\x1b[A\rwaiting ${delta}s"
         sleep 1
     done
@@ -90,7 +278,8 @@ wifi_on() {
 }
 wifi_reboot() {
     local sleep_seconds=""
-    for arg in ${action_args[@]}; do
+    for index in ${!action_args[@]}; do
+        arg=${action_args[$index]}
         if [ -n "${sleep_seconds}" ]; then
             1>&2 echo "wifi_reboot: invalid argument ${arg@Q}. sleep_seconds argument already set to ${sleep_seconds}"
             exit 1
@@ -98,7 +287,7 @@ wifi_reboot() {
         if num_value=$(ack '^\s*\d+\s*$' <<<"${arg}"); then
             sleep_seconds=${num_value}
         else
-            1>&2 echo "wifi_reboot: ignoring unknown argument ${arg@Q}."
+            1>&2 echo "wifi_reboot: ignoring unknown argument ${arg}."
         fi
     done
     if [ -z "${sleep_seconds}" ]; then
@@ -107,20 +296,30 @@ wifi_reboot() {
     wifi_off
     sleep_for ${sleep_seconds}
     wifi_on
-    networksetup -setdnsservers Wi-Fi 127.0.0.1
+    networksetup -setdnsservers Wi-Fi ${dns_servers_ipv4[@]}
 }
+
 case "${action}" in
     "on")
         wifi_on
         ;;
-    "restart"|"reboot")
+    "enable_all_logs")
+        wifi_enable_all_logs
+        ;;
+    "diagnose")
+        wifi_diagnose
+        ;;
+    "restart" | "reboot")
         wifi_reboot
         ;;
     "off")
         wifi_off
         ;;
+    "fix")
+        wifi_fix
+        ;;
     *)
-        1>&2 echo -e "invalid action: ${action@Q}"
+        1>&2 echo -e "invalid action: ${action[@]@Q}"
         1>&2 usage
         exit 1
         ;;
