07ea0b332c0803

diff --git a/gabrielfalcao/opt/libexec/dns-server b/gabrielfalcao/opt/libexec/dns-server
--- a/gabrielfalcao/opt/libexec/dns-server
+++ b/gabrielfalcao/opt/libexec/dns-server
@@ -317,9 +317,12 @@ cfquery() {
 
     if ! filtered=$(2>${stderr} jq ${jq_args[@]} <<< "${response}"); then
         code=$?
-        1>&2 echo -e "command failed: jq ${jq_args[@]} with input=${response@Q}"
-        1>&2 echo -e "stdin: ${response@Q}"
-        1>&2 cat "${stderr}"
+    fi
+    if [ ${code} -ne 0 ]; then
+        1>&2 echo -e "command failed: jq ${jq_args[@]}"
+        # 1>&2 echo -e "command failed: jq ${jq_args[@]} with input=${response@Q}"
+        # 1>&2 echo -e "stdin: ${response@Q}"
+        # 1>&2 cat "${stderr}"
         exit $${code}
     else
         echo -e "${name}"
@@ -369,6 +372,10 @@ git_command_at_path() {
         case "${index}" in
             0)
                 path="${arg}"
+                if [ ! -e "${path}" ]; then
+                    1>&2 echo "path does not exist: ${arg@Q}"
+                    exit 11
+                fi
                 if [ ! -d "${path}" ]; then
                     1>&2 echo -e "${err_prefix}${FUNCNAME[0]} invalid <PATH> argument (not a directory): ${path@Q}"
                     return 1
@@ -401,7 +408,12 @@ git_command_at_path() {
     fi
     local -- stdout=$(mktemp)
     local -a full_cmd=(git ${git_command} ${git_args[@]})
-    if ! (cd ${path} && 2>${stderr} 1>${stdout} ${full_cmd[@]}); then
+    if [ ! -e "${path}" ]; then
+        1>&2 echo "path does not exist: ${arg@Q}"
+        exit 1
+    fi
+
+    if ! (cd "${path}" && 2>${stderr} 1>${stdout} ${full_cmd[@]}); then
         code=$?
         if [ ${code} -ne 0 ]; then
             1>&2 echo -e "running command \`${full_cmd[@]}\' in path ${path@Q} failed exit code ${code}"
diff --git a/gabrielfalcao/opt/libexec/git-q b/gabrielfalcao/opt/libexec/git-q
--- a/gabrielfalcao/opt/libexec/git-q
+++ b/gabrielfalcao/opt/libexec/git-q
@@ -21,6 +21,8 @@ declare -- commit_message=""
 declare -- proceed=""
 declare -i skip_commit=0
 
+declare -- location_type=""
+
 declare -- error_prefix_color_rgb="239;41;41"
 declare -- error_color_rgb="204;0;0"
 
@@ -167,7 +169,6 @@ process_argv() {
 
         commit_message="saves state of workbench \"$(basename ${curdir})\" at $(gdate --utc +"%H:%M:%S") UTC"
     else
-        local -- location_type=""
 
         case "${curdir}" in
             */projects/**/tool/*)
@@ -195,8 +196,47 @@ process_argv() {
     fi
     repl sane
 }
+commit_file() {
+    local -a argv=($@)
+    local -i argc=${#argv[@]}
+    local -i index=0
+    local -i current=0
+    local -- path=""
+    local -i created_ts==0
+    local -i modified_ts=0
+    local -- created_at=''
+    local -- modified_at=''
 
+    if [ ${argc} -eq 0 ]; then
+        1>&2 echo -e "[${FUNCNAME[0]} error]" "missing argument: <PATH>"
+        return 1
+    elif [ ${argc} -gt 1 ]; then
+        1>&2 echo -e "[${FUNCNAME[0]} error]" "takes exactly 1 argument, got ${argc}: ${argv[@]@Q}"
+        return 1
+    fi
+
+    path="${1}"
+    created_ts=$(gstat -c '%W' "${path}")
+    modified_ts=$(gstat -c '%Y' "${path}")
+    created_at=$(gdate --date=@${created_ts} +'%Y-%m-%d %H:%M:%S %Z')
+    modified_at=$(gdate --date=@${modified_ts} +'%Y-%m-%d %H:%M:%S %Z')
+    local -- file_commit_message=""
+
+    if [ ! -e "${path}" ]; then
+        1>&2 echo -e "[${FUNCNAME[0]} error]" "path does not exist: ${path@Q}"
+        return 1
+    fi
+    file_commit_message=$(echo -en "file ${path@Q} created at ${created_at}, modified at ${created_at}\n\n${commit_message}")
+    local -- status_name=''
+
+    echo git commit "${path}" -m "commit ${status_name} at ${location_type} ${file_commit_message}"
+
+}
 main() {
+    local -i now=$(date -u +%s)
+    export GIT_COMMITTER_DATE="$(date --date=@${now} +'%Y-%m-%d %H:%M:%S')"
+    export GIT_AUTHOR_DATE="$(date --date=@${now} +'%Y-%m-%d %H:%M:%S')"
+
     local -a git_cmd=(git commit -am "${commit_message}")
     # local -- result=""
     # until [ -n "${proceed}" ] && 1>/dev/random grep -E '(y(e[ps])?|no?)' <<< "${proceed}"; do
