2026-03-23_07-24-23_UTC

diff --git a/gabrielfalcao/opt/libexec/eject-usb-disks b/gabrielfalcao/opt/libexec/eject-usb-disks
--- a/gabrielfalcao/opt/libexec/eject-usb-disks
+++ b/gabrielfalcao/opt/libexec/eject-usb-disks
@@ -1,83 +1,87 @@
 #!/usr/bin/env bash
 
-set -e
-declare -a volumes=(
-    "NO%20NAME"
-    "nothing%201"
-    "Time%20Machine%20Backups"
-    "UNTITLED"
-    "Untitled"
-    "UNTITLED%202"
-    TemplarKnight
-    WaveMandala1T
-    AiryMcLeod
-    DEFCON-24
-    DR-05
-    GREEN5GB
-    Kindle
-    NONAME
-    NOTHING
-    OF
-    Pedrita1 Pedrita2
-    8x16g
-    SAMDATA-Red
-    Untitled
-    Untitled42
-    WaveMandala
-    crypto
-    GARMIN
-    gabe-private
-    gabe-public
-    gabe-shared
-    gabriel
-    gabriel
-    gabriel-private
-    gabriel-public
-    gabriel-shared
-    gabrielfalcao
-    garuda-bkp
-    garuda-bkp
-    hanuman-bkp
-    medula22
-    mudface-bkp
-    mudface-external
-    newstore-bkp
-    rosencreuz
-    rotekafer
-    sec04212023
-    simba
-    takitaki
-    work-2020-2022
-    X2133
-    "DATA"
-    MalaysianNonSSD
-    nothing
-)
+set -umeTE
+set +f
+set -o pipefail
+unset IFS
+export IFS=$'\n'
 
+declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
+declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+declare -- this_script_path="${script_path}/${script_name}"
 
-function retry-force-eject-volume() {
-    name="${@/\%20/ }"
+if [ "$(id -u)" != "0" ] && [ "$(id -un)" != "root" ]; then
+    sudo -E ${this_script_path}
+    exit 0
+fi
+
+on_exit() {
+    set +x
+}
+on_ctrlc() {
+    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
+    exit 130
+}
+trap on_exit exit
+trap on_ctrlc hup
+trap on_ctrlc int
+trap on_ctrlc bus
+trap on_ctrlc segv
+trap on_ctrlc sys
+
+list_external_volumes() {
+    df | df-mountpoint.gawk
+}
+retry_force_eject_volume() {
+    name="${@}"
     volume="/Volumes/${name}/"
     if [ ! -e "$(basename "${volume}")" ]; then
         return
         # echo -e "\x1b[1;38;5;220m$(basename "${volume}") \x1b[1;38;5;33mdoes not appear to be present\x1b[0m"
-    elif 2>/dev/null sudo diskutil unmount force "$(basename "${volume}")"; then
+    elif 2>/dev/null diskutil unmount force "$(basename "${volume}")"; then
         echo -e "\x1b[1;38;5;106m$(basename "${volume}") \x1b[1;38;5;220mwas ejected forcefully\x1b[0m"
     else
         echo -e "\x1b[1;38;5;220mfailed to eject \x1b[1;38;5;106m$(basename "${volume}") \x1b[1;38;5;145m(maybe in use or already ejected ?)\x1b[0m"
-    fi;
+    fi
+}
+kill_processes_hogging_volume() {
+    name="${@}"
+    volume="/Volumes/${name}"
+    lsof | gawk "(\$0 ~ /${volumes//\/\\\/}/){
+	location = \"\"
+	for (i = 9; i <= NF; i++) {
+		len = length(\$i)
+		last = \"\"
+		if (len > 0) {
+			last = FS
+		} else {
+			last = \"\"
+		}
+		location = sprintf(\"%s%s%s\", location, \$i, last)
+	}
+	print (location)
+}"
 }
 
-function eject-volume() {
-    name="${@/\%20/ }"
+eject_volume() {
+    name="${@}"
     volume="/Volumes/${name}/"
-    if 2>/dev/null sudo diskutil unmount "$(basename "${volume}")"; then
+    if 2>/dev/null diskutil unmount "$(basename "${volume}")"; then
         echo -e "\x1b[1;38;5;154m$(basename "${volume}") \x1b[1;38;5;220mwas ejected\x1b[0m"
     else
-        retry-force-eject-volume "${name}"
-    fi;
+        retry_force_eject_volume "${name}"
+    fi
 }
 
-for name in ${volumes[*]}; do
-    eject-volume "${name}"
-done
+main() {
+    for name in $(list_external_volumes); do
+        eject_volume "${name}"
+    done
+}
+
+# if [ "${0}" == "${script_name}" ]; then
+#     main
+# else
+#     1>&2 echo -e "${script_name} appears to being used as a library by ${0@Q}"
+# fi
+main
diff --git a/gabrielfalcao/opt/libexec/git-q b/gabrielfalcao/opt/libexec/git-q
--- a/gabrielfalcao/opt/libexec/git-q
+++ b/gabrielfalcao/opt/libexec/git-q
@@ -25,6 +25,9 @@ trap on_ctrlc bus
 trap on_ctrlc segv
 trap on_ctrlc sys
 
+cls() {
+    1>&2 echo -en "\x1b[2J\x1b[3J\x1b[H"
+}
 declare -a argv=(${@})
 declare -i argc=${#argv[@]}
 
@@ -56,22 +59,141 @@ declare -i ts_modified=0
 declare -i code=0
 
 declare -- stderr="$(mktemp)"
-
+declare -- here="$(pwd)"
 declare -- git_repo_path=""
-if ! git_repo_path=$(2>${stderr} git rev-parse --show-toplevel); then
+if git_repo_path=$(2>${stderr} git rev-parse --show-toplevel); then
+    code=0
+else
     code=$?
+    1>&2 echo -en "[error]" "cannot find git repo path from ${here@Q}"
+    if [ -s "${stderr}" ]; then
+        1>&2 echo -e ":\n"
+        1>&2 cat "${stderr}"
+    fi
+    1>&2 echo -e "."
+    exit ${code}
 fi
 
-declare -a files_to_git_add=(
-    $(git status --porcelain  | grep -E '[.]log$' | lastcol)
+# cls
+
+if 2>${stderr} cd "${git_repo_path}"; then
+    code=0
+else
+    code=$?
+    1>&2 echo -en "[error]" "cannot change current directory to git repo path ${git_repo_path@Q}"
+    if [ -s "${stderr}" ]; then
+        1>&2 echo -e ":\n"
+        1>&2 cat "${stderr}"
+    fi
+    1>&2 echo -e "."
+    exit ${code}
+
+fi
+
+
+declare -gr sed_regexp='^([?][?]|[?][[:space:]])\s+(([0-9A-Z_a-z./-]+.*?)[.](log|pem|json|txt|sh|std(out|err)([.][a-zA-Z0-9]+)?))$'
+declare -gr sed_to_string='[subexp 0] => \0\n[subexp 1] => \1\n[subexp 2] => \2\n[subexp 3] => \3\n[subexp 4] => \4\n'
+declare -gr sed_command="s,${sed_regexp},${sed_to_string},g; t success q1; :success p"
+
+#########################################################################################
+##### ############################################################################# #####
+##### ###                                                                      #### #####
+##### ### DEBUG                                                                #### #####
+##### ###                                                                      #### #####
+##### 1>&2 echo -en "\x1b[0m\x1b[1;38;5;202m"                                  #### #####
+##### 1>&2 declare -p ${!sed_*}                                                #### #####
+##### 1>&2 echo -en "\x1b[0m\n\x1b[1;38;5;222m"                                #### #####
+##### 2>&1 echo -n "$(git status --porcelain  | sed -E -n "${sed_command}")"   #### #####
+##### 1>&2 echo -en "\n\x1b[0m\n" #####                                        #### #####
+#####                                                                          #### #####
+##### # [subexp 0] => ?? www.gnu.org-invalid-cert/R12.pem                      #### #####
+##### # [subexp 1] => ??                                                       #### #####
+##### # [subexp 2] => www.gnu.org-invalid-cert/R12.pem                         #### #####
+##### # [subexp 3] => www.gnu.org-invalid-cert/R12                             #### #####
+##### # [subexp 4] => pem                                                      #### #####
+#####                                                                          #### #####
+##### # exit 11                                                                #### #####
+#####                                                                          #### #####
+##### ###                                                                      #### #####
+##### ### DEBUG                                                                #### #####
+##### ###                                                                      #### #####
+##### ############################################################################# #####
+#########################################################################################
+
+declare -ga files_to_git_add=()
+files_to_git_add=(
+    # $(git status --porcelain | gawk '{ print $NF }')
+    # $(git status --porcelain  | sed -E -n "${sed_command}" | xargs -Ieachpath echo "${git_repo_path}/eachpath")
+    $(git status --porcelain | grep -E -v '^[?][?]' | gawk '{ print $NF }' | xargs -Ieachpath echo "${git_repo_path}/eachpath")
 )
 
-for item in ${files_to_git_add[@]}; do
-    path="${git_repo_path}/${item}"
-    name="$(basename "${path}")"
-    ts_created=$(gstat -c '%W' "${item}")
-    ts_modified=$(gstat -c '%Y' "${item}")
+if [ ${#files_to_git_add[@]} -eq 0 ]; then
+    files_to_git_add=(
+        $(git status --porcelain | gawk '{ print $NF }' | xargs -Ieachpath echo "${git_repo_path}/eachpath")
+    )
+fi
+
+files_to_git_remove=(
+    $(git status --porcelain | grep -E '^([D]|[[:space:]][D])' | gawk '{ print $NF }' | xargs -Ieachpath echo "${git_repo_path}/eachpath")
+)
+declare -g extension=''
+declare -g ext=''
+declare -g base=''
+declare -g parent=''
+declare -g relative_path=''
+
+# declare -p files_to_git_add
+# exit
+# cls
+
+# 1>&2 declare -p files_to_git_add
+for index in ${!files_to_git_remove[@]}; do
+    path=${files_to_git_remove[${index}]}
+    # relative_path="${path##${git_repo_path}/}"
+    (cd "${git_repo_path}" && git rm --cached -rf "${path}")
+    # (cd "${git_repo_path}" && git rm -rf "${path}")
+    (cd "${git_repo_path}" && git commit "${path}" -m "${path}")
+done
+
+for index in ${!files_to_git_add[@]}; do
+    path=${files_to_git_add[${index}]}
+
+    if [ -z "${path}" ]; then
+        1>&2 echo -e "empty path at index ${index}"
+        continue
+    elif [ ! -e "${path}" ]; then
+        # 1>&2 echo -en "\x1b[0m\x1b[1;38;2;239;41;41m"
+        # 1>&2 declare -p path
+        # 1>&2 echo -en "\x1b[0m"
+        continue
+    fi
+
+    name="$(path name "${path}")"
+    parent="$(path parent "${path}")"
+    base=$(path base -p "${name}")
+    extension=$(path extension -p "${name}" | sed -E 's/^[.]//g')
+    ext=${extension##.}
+
+    # https://git-scm.com/docs/git-commit/2.24.0#Documentation/git-commit.txt-Gitinternalformat
+    ts_created=$(gstat -c '%W' "${path}")
+    ts_modified=$(gstat -c '%Y' "${path}")
     export GIT_AUTHOR_DATE="$(date --date=@${ts_created} +'%s %z')"
     export GIT_COMMITTER_DATE="$(date --date=@${ts_modified} +'%s %z')"
-    git add "${item}" && git commit "${item}" -m "[log] ${name}"
+
+    # 1>&2 echo -en "\x1b[0m\x1b[1;38;2;138;226;52m"
+    # 1>&2 declare -p path name parent base extension ext ts_created ts_modified GIT_AUTHOR_DATE GIT_COMMITTER_DATE
+    # 1>&2 echo -en "\x1b[0m"
+
+    # if [ -z "${extension}" ]; then
+    #     continue
+    # fi
+
+    # 1>&2 echo -en "\x1b[0m\x1b[1;48;5;237m\x1b[1;38;5;222m"
+    # 1>&2 declare -p path parent name base extension ext ts_created ts_modified GIT_AUTHOR_DATE GIT_COMMITTER_DATE
+    # 1>&2 echo -en "\x1b[0m"
+    # echo
+    # echo "git add $'\x22'${name}$'\x22' && git commit $'\x22'${name}$'\x22' -m $'\x22'[log] ${name}$'\x22'"
+    # echo -e "\n\n"
+    git add -f "${path}" && git commit "${path}" -m "${path##${git_repo_path}/}"
+
 done
