wat

diff --git a/gabrielfalcao/opt/libexec/git-q b/gabrielfalcao/opt/libexec/git-q
--- a/gabrielfalcao/opt/libexec/git-q
+++ b/gabrielfalcao/opt/libexec/git-q
@@ -90,7 +90,6 @@ else
 
 fi
 
-
 declare -gr sed_regexp='^([?][?]|[?][[:space:]])\s+(([0-9A-Z_a-z./-]+.*?)[.](log|pem|json|txt|sh|std(out|err)([.][a-zA-Z0-9]+)?))$'
 declare -gr sed_to_string='[subexp 0] => \0\n[subexp 1] => \1\n[subexp 2] => \2\n[subexp 3] => \3\n[subexp 4] => \4\n'
 declare -gr sed_command="s,${sed_regexp},${sed_to_string},g; t success q1; :success p"
@@ -141,7 +140,10 @@ if [ ${#files_to_git_add[@]} -eq 0 ]; then
 fi
 
 files_to_git_remove=(
-    $((git status --porcelain | grep -E '^([D]|[[:space:]][D])' ; echo) | gawk '{ print $NF }' | xargs -Ieachpath echo "${git_repo_path}/eachpath")
+    $(
+        git status --porcelain | grep -E '^([D]|[[:space:]][D])'
+        echo | gawk '{ print $NF }' | xargs -Ieachpath echo "${git_repo_path}/eachpath"
+    )
 )
 declare -g extension=''
 declare -g ext=''
@@ -161,6 +163,8 @@ for index in ${!files_to_git_remove[@]}; do
     # (cd "${git_repo_path}" && git rm -rf "${path}")
     (cd "${git_repo_path}" && git commit "${path}" -m "${path}")
 done
+
+declare -A failures=()
 
 for index in ${!files_to_git_add[@]}; do
     path=${files_to_git_add[${index}]}
@@ -201,6 +205,17 @@ for index in ${!files_to_git_add[@]}; do
     # echo
     # echo "git add $'\x22'${name}$'\x22' && git commit $'\x22'${name}$'\x22' -m $'\x22'[log] ${name}$'\x22'"
     # echo -e "\n\n"
-    git add -f "${path}" && git commit "${path}" -m "${path##${git_repo_path}/}"
-
+    if 2>${stderr} git add -f "${path}" && git commit "${path}" -m "${path##${git_repo_path}/}"; then
+        code=0
+    else
+        code=$?
+        failures["${path}"]=$(cat "${stderr}")
+    fi
 done
+
+declare -i total_failures=${#failures[@]}
+
+if ((${total_failures})); then
+    git add .
+    git commit -am "$(basename $(pwd))"
+fi
diff --git a/gabrielfalcao/opt/libexec/ssh-quick-keygen b/gabrielfalcao/opt/libexec/ssh-quick-keygen
--- a/gabrielfalcao/opt/libexec/ssh-quick-keygen
+++ b/gabrielfalcao/opt/libexec/ssh-quick-keygen
@@ -65,6 +65,7 @@ declare -r default_target_directory="${HOME}/.ssh"
 declare -- target_directory="${HOME}/.ssh"
 declare -- key_type="ed25519" # ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa
 declare -- key_type="ecdsa"   # ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa
+declare -- key_type="rsa"   # ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa
 
 main() {
     if [ ${argc} -eq 0 ]; then
@@ -138,7 +139,8 @@ main() {
 
     if [ "${target_directory}" == "${default_target_directory}" ]; then
         local -- choice=""
-        read -p $(printf "key will be written to ${target_directory}, do you confirm?\n[N/y]: ") choice
+        local -- nl=$'\n[No/yes]: '
+        read -p "key will be written to ${target_secret_key}, do you confirm?${nl}" choice
         case "${choice@L}" in
             n | no | nope)
                 proceed=0
@@ -156,11 +158,21 @@ main() {
     else
         proceed=1
     fi
-
+    local -a make_key_cmd=()
+    make_key_cmd=(ssh-keygen -t "${key_type}" -C "${email}" -l -O hashalg=sha256 -O print-pubkey -Z chacha20-poly1305@openssh.com -f "${target_secret_key}" )
+    # make_key_cmd=(ssh-keygen -t "${key_type}" -C "${email}" -f "${target_secret_key}" -l -O hashalg=sha256 -O print-pubkey -Z chacha20-poly1305@openssh.com)
+    echo "${make_key_cmd[@]}"
     if ((${proceed})); then
         1>&2 echo -e "[${script_name} info]" "writing key to ${target_secret_key}"
-        ssh-keygen -t "${key_type}" -C "${email}" -N "${passphrase@Q}" -f "${target_secret_key}" -l >${target_secret_art}
-        cat "${target_public_key}"
+        if stdout=$(2>${stderr} ${make_key_cmd[@]}); then
+            1>${target_secret_art} echo "${stdout}"
+            code=0
+            cat "${target_public_key}"
+        else
+            code=$?
+            1>&2 echo "${make_key_cmd[@]} failed with code ${code}"
+            1>&2 cat "${stderr}"
+        fi
     else
         1>&2 echo -e "[${script_name} error]" "aborted"
     fi
