opt/libexec/

diff --git a/gabrielfalcao/opt/libexec/setmac b/gabrielfalcao/opt/libexec/setmac
--- a/gabrielfalcao/opt/libexec/setmac
+++ b/gabrielfalcao/opt/libexec/setmac
@@ -44,14 +44,6 @@ trap on_ctrlc bus
 trap on_ctrlc segv
 trap on_ctrlc sys
 
-declare -a argv=(${@})
-declare -i argc=${#argv[@]}
-
-declare -- desired_mac_addr=""
-declare -- desired_dns_ipv4=""
-declare -- current_mac_addr=""
-declare -- current_dns_ipv4=""
-declare -- iface="en0"
 declare -- stderr=""
 declare -i code=0
 stderr=$(mktemp)
@@ -70,73 +62,149 @@ trap on_ctrlc bus
 trap on_ctrlc segv
 trap on_ctrlc sys
 
-iface="en0"
-desired_dns_ipv4="127.0.0.1"
+declare -- desired_mac_addr=""
+declare -- desired_dns_ipv4=""
+declare -- current_mac_addr=""
+declare -- current_dns_ipv4=""
+declare -- iface="en0"
+declare -- svice="Wi-Fi"
+declare -- desired_dns_ipv4="127.0.0.1"
 
 # declare -- nowhex=$(date | sha256sum | gawk '{print $1}')
 # desired_mac_addr="10:CA:81:${nowhex[@]:4:2}:${nowhex[@]:2:2}:${nowhex[@]:0:2}"
 desired_mac_addr="10:CA:81:02:19:58"
-desired_mac_addr="10:CA:81:15:11:4c" # PRECIA
 desired_mac_addr="00:0B:79:15:11:4c"
 desired_mac_addr="00:A0:D0:15:11:4c"
+desired_mac_addr="58:EE:CE:15:11:4c" # 58:EE:CE => "Icon Time Systems"
 desired_mac_addr="00:04:B4:15:11:4c" # CIAC
-desired_mac_addr="20:DE:88:21:17:76"
-desired_dns_ipv4="127.0.0.1"
+desired_mac_addr="20:DE:88:21:17:76" # IC Realtime LLC
+desired_mac_addr="10:CA:81:15:11:4c" # PRECIA
+
+# desired_mac_addr="00:1F:B0:21:17:76"
 
 current_mac_addr=$(ifconfig "${iface}" ether | gawk '$1 ~ /ether/ { print $NF }')
-current_dns_ipv4=$(networksetup -getdnsservers Wi-Fi)
+current_dns_ipv4=$(networksetup -getdnsservers ${svice})
+declare -i run_again=0
+declare -i static_dhcp=0
 
-hostname langley.local
-1>&2 echo "current_dns_ipv4 ${current_dns_ipv4}"
-if [ "${current_dns_ipv4}" != "${desired_dns_ipv4}" ]; then
-    networksetup -setairportpower ${iface} off || false
-    networksetup -detectnewhardware
-    if networksetup -setdnsservers Wi-Fi 127.0.0.1; then
-        1>&2 echo -e "\x1b[1;38;2;115;210;22mADDR SET\x1b[0m"
-    else
-        1>&2 echo -e "\x1b[1;38;2;204;0;0mDNS NOT SET\x1b[0m"
+declare -i index=0
+declare -i current=0
+declare -- arg=""
+declare -- pos=""
+declare -a pids_to_kill=()
+
+pids_to_kill=(
+    $(ps aux | gawk "BEGIN { IGNORECASE=1;} {
+        if (\$0 ~ /(Wi.?Fi|DNSResponder)/) {
+            if (! \$2 ~ /(${$}|${PPID})/) {
+                print \$2
+            }
+        }
+    }")
+)
+for index in ${!argv[@]}; do
+    current=$(($index + 1))
+    arg="${argv[$index]}"
+    pos="$(printf '%*s of %s' ${#argc} ${current} ${argc})"
+    if [[ "${arg}" =~ ([-][sSfFmM]|[-][-](static|fixed|manual(ly)?)([-](dhcp|ip))?) ]]; then
+        # 1>&2 echo -e "\x1b[1;38;2;44;137;175mUsing static address as per \x1b[1;38;2;244;214;110m${arg@Q} \x1b[0m"
+        1>&2 echo -e "\x1b[1;38;2;236;148;234mUsing static address as per \x1b[1;38;2;234;235;255m${arg} \x1b[0m"
+        static_dhcp=1
     fi
-    networksetup -setairportpower ${iface} on || false
+done
 
+if [ ${static_dhcp} -eq 0 ]; then
+    1>&2 echo -e "\x1b[1;38;2;236;148;234msetting ${iface} to DHCP \x1b[0m"
 fi
 
-if [ "${current_mac_addr}" != "${desired_mac_addr}" ]; then
+disable_wifi() {
+    local -i target_pid=-1
+    for target_pid in ${pids_to_kill[@]}; do
+        kill -9 "${target_pid}"
+    done
     networksetup -setairportpower ${iface} off || false
-    if 2>${stderr} ifconfig ${iface} lladdr ${desired_mac_addr}; then
-        code=0
-        1>&2 echo -e "\x1b[1;38;2;237;212;0mLLADDR SET: ${desired_mac_addr}\x1b[0m"
-        networksetup -setairportpower ${iface} on || true
-        1>&2 cat "${stderr}"
-    else
-        code=$?
-        1>&2 echo -e "\x1b[1;38;2;239;41;41mLLADDR NOT SET\x1b[0m"
-        1>&2 cat "${stderr}"
-        networksetup -setairportpower ${iface} on
-        networksetup -detectnewhardware
-    fi
-    if 2>${stderr} ifconfig ${iface} ether ${desired_mac_addr}; then
-        code=0
-        1>&2 echo -e "\x1b[1;38;2;237;212;0mETHER SET: ${desired_mac_addr}\x1b[0m"
-        networksetup -setairportpower ${iface} on || true
-        1>&2 cat "${stderr}"
-    else
-        code=$?
-        1>&2 echo -e "\x1b[1;38;2;239;41;41mETHER NOT SET\x1b[0m"
-        1>&2 cat "${stderr}"
-        networksetup -setairportpower ${iface} on
-        networksetup -detectnewhardware
-    fi
-    exit ${code}
-else
-    networksetup -setairportpower ${iface} off || false
-    networksetup -detectnewhardware
-    sleep 1
-    1>&2 echo -e "\x1b[1;38;2;252;175;62maddr already set\x1b[0m"
+}
+enable_wifi() {
     networksetup -setairportpower ${iface} on
-    networksetup -detectnewhardware
+}
+run_once() {
+    if (($static_dhcp)); then
+        networksetup -setv6off ${svice}
+        networksetup -setmanual ${svice} 192.168.8.37 255.255.255.0 192.168.8.1
+    else
+        networksetup -setdhcp ${svice}
+    fi
+    hostname main.langley
+    # 1>&2 echo "current_dns_ipv4 ${current_dns_ipv4}"
+    if [ "${current_dns_ipv4}" != "${desired_dns_ipv4}" ]; then
+        disable_wifi
+        networksetup -detectnewhardware
+        if networksetup -setdnsservers ${svice} 127.0.0.1; then
+            1>&2 echo -e "\x1b[1;38;2;115;210;22mADDR SET\x1b[0m"
+        else
+            1>&2 echo -e "\x1b[1;38;2;204;0;0mDNS NOT SET\x1b[0m"
+        fi
+        enable_wifi
+    fi
 
-fi
+    if [ "${current_mac_addr@U}" != "${desired_mac_addr@U}" ]; then
+        disable_wifi
+        if 2>${stderr} ifconfig ${iface} lladdr ${desired_mac_addr}; then
+            code=0
+            1>&2 echo -e "\x1b[1;38;2;204;241;122mLLADDR SET: \x1b[1;38;2;240;192;76m${desired_mac_addr}\x1b[0m"
+            enable_wifi
+            1>&2 cat "${stderr}"
+            run_again=0
+        else
+            code=$?
+            # 1>&2 echo -e "\x1b[1;38;2;239;41;41mLLADDR NOT SET, will retry\x1b[0m"
+            # 1>&2 cat "${stderr}"
+            run_again=1
 
+            enable_wifi
+            networksetup -detectnewhardware
+        fi
+        if 2>${stderr} ifconfig ${iface} ether ${desired_mac_addr}; then
+            code=0
+            1>&2 echo -e "\x1b[1;38;2;253;203;176mETHER SET: \x1b[1;38;2;195;36;84m${desired_mac_addr}\x1b[0m"
+            enable_wifi
+            1>&2 cat "${stderr}"
+        else
+            code=$?
+            run_again=1
+            1>&2 echo -e "\x1b[1;38;2;239;41;41mETHER NOT SET\x1b[0m"
+            1>&2 cat "${stderr}"
+            enable_wifi
+            networksetup -detectnewhardware
+        fi
+        return ${code}
+    else
+        disable_wifi
+        networksetup -detectnewhardware
+        sleep 1
+        1>&2 echo -e "\x1b[1;38;2;249;194;43maddr already set to \x1b[1;38;2;145;219;105m${desired_mac_addr}\x1b[0m"
+        enable_wifi
+        networksetup -detectnewhardware
+    fi
+    networksetup -getinfo "${svice}"
+}
+setup_lan_turtle_if_connected() {
+    # lan turtle
+    declare -- turtle_current_ifconfig=""
+    turtle_svice="USB 10/100 LAN" # 00:04:63:54:55:52
+    turtle_iface="en8"
+    turtle_self_ip=172.16.84.192
+    turtle_gateway=172.16.84.1
+    turtle_netmask=255.255.255.0
+
+    if turtle_current_ifconfig=$(2>/dev/null ifconfig ${turtle_iface}); then
+        # lan turtle appears to be plugged!
+        1>&2 echo -e "🛜 it appears we're turtleling 🐢"
+        networksetup -setv6off ${turtle_svice}
+        networksetup -setmanual ${turtle_svice} ${turtle_self_ip} ${turtle_netmask} ${turtle_gateway}
+    fi
+
+}
 # IyBXSVAgIyBjb21tYW5kX2luZm9fYXRfaW5kZXgoKSB7CiMgV0lQICMgICAgIGxvY2FsIC1hIGxvY2FsX2FyZ3Y9KCAkQCApCiMgV0lQICMgICAgIGxvY2FsIC1pIGxvY2FsX2FyZ2M9JHsjbG9jYWxfYXJndltAXX0KIyBXSVAgIyAgICAgbG9jYWwgLWkgaW5kZXg9JHtsb2NhbF9hcmd2WzBdfQojIFdJUCAjICAgICBsb2NhbCAtLSBzdGRlcnI9IiIKIyBXSVAgIyAgICAgbG9jYWwgLS0gc3Rkb3V0PSIiCiMgV0lQICMgICAgIGxvY2FsIC0tIGV4aXRfY29kZT0iIgojIFdJUCAjICAgICBsb2NhbCAtLSBzaGVsbF9jb21tYW5kPSIiCiMgV0lQICMgIyAgICAgbG9jYWwgLS0gdmFyX25hbWU9JHt9CiMgV0lQICMgICAgIGlmIHN0ZGVycj0ke3N0ZG91dF9tYXBbJGluZGV4XX0gJiYgXAojIFdJUCAjICAgICAgICAgICAgIHN0ZG91dD0ke3N0ZG91dF9tYXBbJGluZGV4XX0gJiYgXAojIFdJUCAjICAgICAgICAgICAgICBleGl0X2NvZGU9JHtzdGRvdXRfbWFwWyRpbmRleF19ICYmIFwKIyBXSVAgIyAgICAgICAgICAgICAgc2hlbGxfY29tbWFuZD0ke3N0ZG91dF9tYXBbJGluZGV4XX07IHRoZW4KIyBXSVAgIwojIFdJUCAjCiMgV0lQICMKIyBXSVAgIyB9CiMgV0lQICMKIyBsYXN0X3N0ZGVycigpIHsKIyAgICAgbG9jYWwgLWkgaW5kZXg9JHsjc3RkZXJyX21hcFtAXX0KIyAgICAgaWYgWyAke2luZGV4fSAtZ3QgMCBdOyB0aGVuCiMgICAgICAgICBlY2hvICIke3N0ZGVycl9tYXBbJGluZGV4XX0iCiMgICAgIGVsc2UKIyAgICAgICAgIHJldHVybiAxCiMgICAgIGZpCiMgfQojIHRyeV9zaGVsbF9jb21tYW5kKCkgewojICAgICB1bnNldCBJRlMKIyAgICAgbG9jYWwgLWEgbG9jYWxfYXJndj0oICRAICkKIyAgICAgbG9jYWwgLWkgbG9jYWxfYXJnYz0keyNsb2NhbF9hcmd2W0BdfQojICAgICBsb2NhbCAtaSBleGl0X2NvZGU9MAojICAgICBsb2NhbCAtLSBzdGRlcnI9JChta3RlbXApCiMgICAgIGxvY2FsIC0tIHN0ZG91dD0kKG1rdGVtcCkKIyAgICAgbG9jYWwgLS0gZnVsbF9jb21tYW5kX3N0cmluZz0iJHtsb2NhbF9hcmd2W0BdfSIKIyAgICAgbG9jYWwgLWkga2V5PSR7I3NoZWxsX2NvbW1hbmRfY2FsbHNbQF19CgojICAgICBpZiAhIDI+JHtzdGRlcnJ9ICR7bG9jYWxfYXJndltAXX0gfCB0ZWUgJHtzdGRvdXR9OyB0aGVuCiMgICAgICAgICBleGl0X2NvZGU9JD8KIyAgICAgZmkKIyAgICAgZXhpdF9jb2RlX21hcCs9KFsiJHtrZXl9Il09IiR7ZXhpdF9jb2RlfSIpCiMgICAgIHN0ZGVycl9tYXArPShbIiR7a2V5fSJdPSIkKDI+L2Rldi9yYW5kb20gY2F0ICIke3N0ZGVycn0iIHx8IHRydWUpIikKIyAgICAgc3Rkb3V0X21hcCs9KFsiJHtrZXl9Il09IiQoMj4vZGV2L3JhbmRvbSBjYXQgIiR7c3Rkb3V0fSIgfHwgdHJ1ZSkiKQojICAgICBzaGVsbF9jb21tYW5kX21hcCs9KFsiJHtrZXl9Il09IiR7ZnVsbF9jb21tYW5kX3N0cmluZ30iKQoKIyAgICAgYmFzaCAtYyAicm0gLWYgJHtzdGRlcnJAUX0gfHwgdHJ1ZSIgfHwgdHJ1ZQojICAgICAjIGlmICgoICRleGl0X2NvZGUgKSk7IHRoZW4KIyAgICAgIyAgICAgcmV0dXJuCiMgICAgICMgZmkKIyAgICAgcmV0dXJuICR7ZXhpdF9jb2RlfQojIH0KIyBjdXJyZW50X2V0aGVyKCkgewojICAgICBsb2NhbCAtLSBtYWNfYWRkcj0iIgojICAgICBpZiBtYWNfYWRkcj0kKHRyeV9zaGVsbF9jb21tYW5kIGlmY29uZmlnICR7aWZhY2V9IGV0aGVyIHwgZ3JlcCAtRSAnZXRoZXInIHwgYXdrICd7IHByaW50ICQyIH0nKTsgdGhlbgojICAgICAgICAgZWNobyAiJHttYWNfYWRkcn0iCiMgICAgIGVsc2UKIyAgICAgICAgIDE+JjIgZWNobyAtZSAiY291bGQgbm90IHJldHJpZXZlIG1hYyBhZGRyZXNzIGZyb20gaW50ZXJmYWNlICR7aWZhY2VAUX0iCiMgICAgICAgICByZXR1cm4gMQojICAgICBmaQojIH0KIyAjIG5ldHdvcmtzdG9vbCgpewojICMgICAgIGxvY2FsIC1hIGxvY2FsX2FyZ3Y9KCAkQCApCiMgIyAgICAgbG9jYWwgLWkgbG9jYWxfYXJnYz0keyNsb2NhbF9hcmd2W0BdfQojICMgICAgIGxvY2FsIC0tIHZhbHVlPSIiCiMgIyAgICAgaWYgbGluZT0kKG5ldHdvcmtzZXR1cCAtZ2V0YWlycG9ydHBvd2VyICIke2lmYWNlfSIpOyB0aGVuCgojICMgYWlycG9ydF9wb3dlcl9pc19vbigpIHsKIyAjICAgICBsb2NhbCAtLSBsaW5lPSIiCiMgIyAgICAgbG9jYWwgLS0gdmFsdWU9IiIKIyAjICAgICBpZiBsaW5lPSQobmV0d29ya3NldHVwIC1nZXRhaXJwb3J0cG93ZXIgIiR7aWZhY2V9Iik7IHRoZW4KIyAjICAgICBpZiBzdWRvIG5ldHdvcmtzZXR1cCAtc2V0YWlycG9ydHBvd2VyICR7aWZhY2V9IG9mZjsgdGhlbgojICMgICAgICAgICAxPiYyIGVjaG8gInRyeWluZyB0byBzZXQgZXRoZXIgYWRkciB3aXRoIGFpcnBvcnQgcG93ZXIiCiMgIyAgICAgdW50aWwgMj4vZGV2L3JhbmRvbSBzdWRvIGlmY29uZmlnICR7aWZhY2V9IGV0aGVyICR7ZGVzaXJlZF9hZGRyfTsgZG8KIyAjICAgICAgICAgc3VkbyBuZXR3b3Jrc2V0dXAgLWRldGVjdG5ld2hhcmR3YXJlCiMgIyAgICAgICAgIHN1ZG8gbmV0d29ya3NldHVwIC1zZXRhaXJwb3J0cG93ZXIgJHtpZmFjZX0gb24KIyAjICAgICAgICAgY3VycmVudF9hZGRyPSQoaWZjb25maWcgJHtpZmFjZX0gZXRoZXIgfCBncmVwIGV0aGVyIHwgYXdrICd7IHByaW50ICQyIH0nKQojICMgICAgIGRvbmUKIyAjIH0KCiMgIyB0cnlfc2V0bWFjKCkgewojICMgICAgIGlmIHN1ZG8gbmV0d29ya3NldHVwIC1zZXRhaXJwb3J0cG93ZXIgJHtpZmFjZX0gb2ZmOyB0aGVuCiMgIyAgICAgICAgIDE+JjIgZWNobyAidHJ5aW5nIHRvIHNldCBldGhlciBhZGRyIHdpdGggYWlycG9ydCBwb3dlciIKIyAjICAgICB1bnRpbCAyPi9kZXYvcmFuZG9tIHN1ZG8gaWZjb25maWcgJHtpZmFjZX0gZXRoZXIgJHtkZXNpcmVkX2FkZHJ9OyBkbwojICMgICAgICAgICBzdWRvIG5ldHdvcmtzZXR1cCAtZGV0ZWN0bmV3aGFyZHdhcmUKIyAjICAgICAgICAgc3VkbyBuZXR3b3Jrc2V0dXAgLXNldGFpcnBvcnRwb3dlciAke2lmYWNlfSBvbgojICMgICAgICAgICBjdXJyZW50X2FkZHI9JChpZmNvbmZpZyAke2lmYWNlfSBldGhlciB8IGdyZXAgZXRoZXIgfCBhd2sgJ3sgcHJpbnQgJDIgfScpCiMgIyAgICAgZG9uZQojICMgfQojIHNldG1hYygpIHsKIyAgICAgbG9jYWwgLWEgbG9jYWxfYXJndj0oICRAICkKIyAgICAgbG9jYWwgLWkgbG9jYWxfYXJnYz0keyNsb2NhbF9hcmd2W0BdfQojICAgICB1bnRpbCAyPi9kZXYvcmFuZG9tIHN1ZG8gaWZjb25maWcgJHtpZmFjZX0gZXRoZXIgJHtkZXNpcmVkX2FkZHJ9OyBkbwojICAgICAgICAgc3VkbyBuZXR3b3Jrc2V0dXAgLXNldGFpcnBvcnRwb3dlciAke2lmYWNlfSBvZmYKIyAgICAgICAgIHN1ZG8gbmV0d29ya3NldHVwIC1kZXRlY3RuZXdoYXJkd2FyZQojICAgICAgICAgc3VkbyBuZXR3b3Jrc2V0dXAgLXNldGFpcnBvcnRwb3dlciAke2lmYWNlfSBvbgojICAgICAgICAgY3VycmVudF9hZGRyPSQoaWZjb25maWcgJHtpZmFjZX0gZXRoZXIgfCBncmVwIGV0aGVyIHwgYXdrICd7IHByaW50ICQyIH0nKQojICAgICBkb25lCiMgfQo=
 # IyAjIDNDOjE5OjE1ICMgR0ZJIENocm9ubyBUaW1lCgojIEY0OkI3OjJBICAgIFRJTUUgSU5URVJDT05ORUNUIExURAojIDNDOjE5OjE1ICAgIEdGSSBDaHJvbm8gVGltZQojIDAwOjEyOkU1ICAgIFRpbWUgQW1lcmljYSwgSW5jLgojIDAwOjAxOkQ0ICAgIExlaXN1cmUgVGltZSwgSW5jLgojIEU0OkYzOjY1ICAgIFRpbWUtTy1NYXRpYywgSW5jLgojIDYwOjEyOjgzICAgIFRTQiBSRUFMIFRJTUUgTE9DQVRJT04gU1lTVEVNUyBTLkwuCiMgQTA6OUE6NUEgICAgVGltZSBEb21haW4KIyAwMDowQjpENyAgICBET1JNQSBUaW1lICsgQWNjZXNzIEdtYkgKIyAwMDowOTo3MSAgICBUaW1lIE1hbmFnZW1lbnQsIEluYy4KIyAwMDoxMTo2RCAgICBBbWVyaWNhbiBUaW1lIGFuZCBTaWduYWwKIyAwMDoxODpDNyAgICBSZWFsIFRpbWUgQXV0b21hdGlvbgojIDAwOjA1OkY4ICAgIFJlYWwgVGltZSBBY2Nlc3MsIEluYy4KIyA3QzozODo2QyAgICBSZWFsIFRpbWUgTG9naWMKIyA1ODpFRTpDRSAgICBJY29uIFRpbWUgU3lzdGVtcwojIDAwOjYwOjk1ICAgIEFDQ1UtVElNRSBTWVNURU1TLCBJTkMuCgojIHVzZXJuYW1lIDYyOTA1CiMgcGFzc3dvcmQgNGEwYWZkMGQ4OWEzZmI5NTMyYjExZTlhMjE0ZGIxYWVmNWVmNjg2NjAzMGIwM2I0NDA1YWQxNTg4ODg5NmJmYQojIEg0c0lBR09qSm1rQ0E2MmFVVy9pT0JESDMvZFRWSDFlN2NaSkNJRTNTdGc5SkVxanduWlBPcDFXanUwVWE0UE5KWUV1T3QxM1A1dEFZVWtjT3dtVldnRzJmM2JHNC9GL2h2NzE0ZTd1WC9GN2QzZFA4ZjN3N243Q1lKU1FMenhkMzM4c1BtZHdUV1RMdlhqNzM4ZnIvdDhoQy9nYVVsYnFmbnkvZzhuMjhNR1U1U1JsSlA4S2MvSUc5d0haVVVRK2ZSL05qNitBZkQzbWpCR1VVODR1UHczRDhOendDU2hYc25pak9WcHBWOEpaTmVFWllzb0ZKbHdVVm1nTkdpRkVzbXk1MytnUmlvZVpNQVEzanh3VGNFMTRieWtiT09RVERjMDJwd21icTNCaHluT09lR0wwZ05OdzUzNFdmenpscmwxT1g0UDU4Y3kzT2NIVm1BVkpwYnZNYUpiclVmUGw1SGsrV1ZhVFhwTE9maVFSVTZ3ZDNyT3M2dkhTWk5JdUJlZHJ3aVB5TFNPcEZxamFMY3BUbXU5RG5sQzAxMElXRzRKb1RGV0dEa2dNdDBrdWwzWUNhNUdXMmt4ZEdkSlVqMzkrMHg4ejExY1FwR1huY3BnTzRka0RxNmN3TWN5eU41N3F0OXlGRm95eGhmMEJkT0pvMEhQc0NBQXlnRFp3Y1FRZ2lYc2s5bnpQc3h3cnNweklkYTBleEtEbmk1K0JGOFZRTVgwWWpyYjVpckNjSWloRDVPbUFhdGNUanNMUDR6OUdZVFgzYVNOaG50VXhHc3E0Wkd4bE5jTFl5TldJaDVUaVY5THhVV1pvTTBFci9reitHYThJK3RuQkpEdjNnVEk4ZzB5R3JGS1F2Mm92Y1dlak9UQWkyeTNJdGhIWmFVRjJqTWh1QzdKclJPNjFJUGVNeUY0THNtZEU3cmNnOTQzSWZndXliMFFlTkNVdkZ0UEF6S0dCMVladDV0SUF0R0diT1RXdzI3RE4zQm80YmRobWpnM2NObXd6MXdhOU5td3o1d1plRzdhdkZLay9RczUrSUJuMEkvNnI1Q2ZYSGNvWDdaTXFZQWRaUGcxRnZ2VUdVMHpacTVHQ1ZXamdnMnF0VEJyT1RTWFdJMlJibUVqRklOSXJIZGh1QUJhU2hOZnhBcExBL1pJYWFBSkhJZDFDWWE5cE9NSTRGZGxXUzZPZGNqNHBVRmg3Z2ZLZU9wcUtsSS8xUDRxOE1weTNYRjlBWVRMZnJxUFdXY1F5cGErdkpLMzByb3Uyc2hja0l0ZlBucGlXYWplaFByR0FyQ0hENmxCdzlJcks5VjYxbHlOQkxsUTBNbUxiVGRuQkgrUFFpT3cwSmRjazdITG9OOFlPKzA5d3grejJkOWgwMCszOFhTMXRHekdTUDhMc1p3ZmNIT1kzZUVSQjZWTEFrWWdYd2pCUHA3akRzNHdUS3RLNlRvaXVFVkl5YnJJdjd3dFpFTVFadnNseU9xUGVGN1ZjMGZRMmErcEtPcFpZam5YU0xxRDU0bWxIVXBINGtoc2NpRENsYTVqdUJWUVcyMXBmSkFkYkhYYnRSakI1dFJtVkVPdXZvaE5xaWhOaXBFcUFYMU9Ua3BTQVpxaW9XaHN0THlCU2dUMVFUTk9pMEEyVFpGKy8xbU5SdkpCd2xkZGNxVmRsZmJab092WnJNS1hkZFVwaEl0MmtSY1htVVJ3SWlxQ0JOcTV6NFhOUnRhVy9pZHdoV0tGTng5T1U4VzJLeUxwS21weWJUQ3VnNXhGMkE1amkxdG9VWnh5enRwZEZkanJaN1JFaXpzVDBWN0h0dU10MmUyRktCRWtsQVMrYXkxcnEwQ1F5RlBKNktLaWF6R0UzbkVPak1pK0dPZzNKYzg2SW1sdk1Xd3pYbXRmMkxYZm85QkVhQWdkYlEyaFoxbkQ0dWFmTzd6Mk44UFowNG5obnhyYWJzbVU2S3NKU1RGKzNLY0ZHY3poTjU5QnQ2Y1ZZdHlsYnZhbkxZQ0lIbjFXMEhKKzBQamtDSi9mQlExOTRhcW9jYTFnWHp5WFNkU05KdlppTlJtTzFGWjlKSmpWRFoxVjdXdFlpMzhaeEI0eTV3TDQ0VGJZOFNFNFVhYnhkNnNrWllSTWY2ZldJclM3T2VrY3hhY0tKaVMrVzV0bkFIam9vam9jeElmN1E2L1Y3TlNIbEJ1bUJkeVBaKytLZE5POG9TZmhicHl2a3hhdTVxbjl2TnYvQzhuS1UzUkFLNnE2TFc4bHo3NWJ5M091c3VRNitzWmpSdlBvK0tacktGU0p4cERVNHV3RXUySXRPZGFHOUdPYzBRR292aXkvTDUwNWZtZTY4ZWJqc0tGVlhiNXpsT2Y5SlN2L2ZjLzM1T1g3NDdxQWZZU3Z1Vy8wQjltMDNnaVRHQTI4UVc4Q1BZaGNCQ3dBcnNrVVgzNDE5UlFCODJBbzhHMjAyaVQ0VUZMMXFNR1BJa01HTmVPd21RUi8rL3ZBL2pvZTJFaHNsQUFBPQojIDAwOjA5OjcxOjIxOjE3Ojc2IC0gR2xpbSBSb3V0ZXIgU3Bvb2YKIyA5NDo4MzpjNDoxYzoyNTowNiAgLSBHTGltIFJvdXRlciBPcmlnCiMgMTA6MGI6YTk6MmY6MTQ6MDggIyBUNDIwIC0gMTkyLjE2OC4xOC4xNTUgLSAyODA0OjM3Y2M6MTNkMDphMDAwOmNmZjI6YTU4Yjo4YWE5OmMwNmYKIyBiODoyNzplYjpmNjo1Mjo1ZSAjIG9sZCBwaSAxOTIuMTY4LjE4LjE1NyAtIDI4MDQ6MzdjYzoxM2QwOmEwMDA6NzI1NjplZjA4OmMyYjI6ZWJiNQojIGRjOmE2OjMyOmYzOjM2OjM0ID8/IDE5Mi4xNjguMTguMTc4CiMgN2U6MjM6ZjI6ZWQ6YmY6OTggMTkyLjE2OC4xOC4xODAKIyBtYWxhID0+IDE0OmFjOjYwOjEzOmU2Ojc3ID0+IDE5Mi4xNjguMTguMjAyCgojIEg0c0lBRHBXTTJrQ0E5MmFiVy9iTmhESHY0cWdvY01HekxINEpOdU1IYUNwOXlKWTF4UzFzYmNESlZFeFVVVVNKRHBwdnYxSVBjU1BqUzJEbnVRQVFXSlRkLzg3aWtmK2NJckdrbmtSdDU1RklCY1RlNFEvMkphWFpBSFBKamF3TFJhSmgzaGkrenlXUExNdG4wZFJ5b0pBeEE4VDJ5bS81eW56Nis4aW1OZ0JmNHBFTHRYRmlPWDV4Sjd5cDNrUm92N3dXVjJkQi9iTldIcEo4S0wrWk51bWN5RWpyZzJDT2k4dy9MQWpXT3VvNzhMbjFoZjJ5TWQ5R1d5NHdaKzdmVTB5YWQxTmQxekl3VWgzY1ppYzREYVRUQzd6YlVmby9OenhVeExIM0pjaWlhM3BNbVA2UXhQMys1U1hUbFhRdnN6MjNXMXRYdDdzdlRxcUN1cFkrbTdHeVhQRzBvbXRQQUx4Vks2NGVQck1QQjRwUDcwSS96cnFXcHg0S2xpa2h3dWJhTk5nTFpRZUtkeHRTK3AxbjlpOTNxYjRtbTZ2Tis2ckVUV1hRdkJtN0MybFZMY25seS9hTXhCNUdyRVhHaWN4djFaNkw2a2FMRTNLNHZSay9HY2c1R1lHZXVSV0tvc2s5aVBoZjUvWWVxUmNOUjM0TjdrUStaVUlmcjlXZWZWTE9mV2huR0taanM1MmZ3N1ZITzdpZENuWGI1RFFBMVdHa3YrUXBhWFlORnRMc2hEUXc4cVgxWFA1bUtacnhvdU1oeFA3bCsyYnE2WjIrN0EydWRuU2V4UjFrR0p1YW1KMTlzOExJWGxQNzJsT3k2VysxdG4xQXU0blpURlZFN3U1LzJ2Y1p6ZS94bDZlWHE4eStzUlVHTjQ4cVEyLzA1UFNNanpTaWRWMVVtMlh2YVVON2ZXRFlsVnowNkxtOUFHaGwybzJ1NXVTaG5Ka1MrNHVaWEh3Ti9PMUhuQXA0OVFuZERDZ2VFQmhNRloxQkVid0NyakRLNkIvUU1Ob1lEZjU4ckRSNGU3alNNVDhHTVcxbmU1c0tWWW4wVnlVMVFzY2E1RXNzOXdpMXFPSWw1TG4xakVCdHZTcnZSdXJGYStyT1hvcDk4R3E5SXZCMjhMU3ozTXJTZFdDODNKdjNsWWIrN1dJOHFLeXdmcCtuWExKUkpTdnR1MGJRZk1GeTRxYTNUdzNUazRFMW9uOFlVMlpaRHFkbVE1aGZmUjluaCtYVTZ6eVQxT0RTYUZWVXM0cUw2MGovSW93cnlmYy93a05jQWdhNEcxb0lQaDFJU0kvK1paOFg4Ny8yUThRRldQVHpBeE1RS3N3QWNmQkJEU0JDZWdpVE1ERnd3UVlob25TWTVqQ0VSMFNpaDBhamlnYWJjTUVqSXpCQkp3Qkprb1RGQ3l4aUhzbWxvRDJXQUs2eUJMdzdsa0NEN0VFbnRhQVFITU5DR3lWR2ZBNFpzQW16SUJkWkFhOGVHWkF3OHhRZWtOSUVhZWhRL21RRGdkME1OeHBRS0F4WnFodzkyRm9HQm9iKzlBTUpHQjdrSURHem1QOGVoN1haL0dVUjF6eUpuU0E3NTRPNkJBZDBOdDBDS01rNDJxWDcyZUVVcThOekpBQ3RVb0tkQndwVUJOU29DNlNBbDA4S1pCaFVpRDluSWM2SG1VakNrTUtNSFYyU0VHSU1WS2dNM1FYU2hPNTFhTXFmS2IyQXJWSER0VEY5Z0s5ZTREZ1F3REJwN1VYMkZ4N2dWdUZCajRPR3JnSk5IQVhvWUV2SGhxNGhBWXdCUTJseHlEMVE0clViMGhEVEFmaE5qUUc1cUNCejlGZVlQUHRCVzRQRXJoVDdRVis5M1FnaCtoQTNxYkROeDQ4aXQ2WFJKMElBTzRIaFFxeFlXV0dHYVJWWnBEam1FR2FNSU4wa1JuazRwbEJERE5ENlFXUUFrSVJvZ09mRGpGMTBUWXpFRGJHREhJT1poRHp6Q0R0TVlOMGlobmszVFBEUGNRTTk3U093alhYVWJpdDBzRTlqZzV1RXpxNFhhU0RlL0YwY0EwL2hsSjZBMDRob2lHa1BLQmVTRWU3LzdCd2pOSEJQY05qS0tWWnZqQmx3VE05aEhMYlk0WGJ4WWRRYnJ2STZGZXZOdmVMbDZ0di9nTTZlSTVhWkMwQUFBPT0K
 # NTP servers
@@ -208,3 +276,19 @@ fi
 # 00:0B:D7 => "DORMA Time + Access GmbH"
 
 # 00:04:B4:27:01:60
+
+setup_lan_turtle_if_connected
+run_once
+while ((${run_again})); do
+    run_once
+done
+
+# #\(00[:]?04[:]?B4\|00[:]?0B[:]?79\|00[:]?A0[:]?D0\|10[:]?CA[:]?81\|20[:]?DE[:]?88\|58[:]?EE[:]?CE\)
+# grep -Ei '^((00[:]?04[:]?B4|00[:]?0B[:]?79|00[:]?A0[:]?D0|10[:]?CA[:]?81|20[:]?DE[:]?88|58[:]?EE[:]?CE)|.*(time|cia).*)' ~/opt/etc/macaddrvendors.txt
+
+# router MACS
+
+# 00:30:EA:47:4C:49 # TeraForce Technology Corporation
+# 00:06:4c:45:45:54 # Invicta Networks, Inc. LEET
+# 00:06:6c:33:33:54 # Invicta Networks, Inc. l33T
+# 00:04:B4:5a:4f:4d # CIACZOM
