wat

diff --git a/gabrielfalcao/opt/libexec/ssh-quick-keygen b/gabrielfalcao/opt/libexec/ssh-quick-keygen
--- a/gabrielfalcao/opt/libexec/ssh-quick-keygen
+++ b/gabrielfalcao/opt/libexec/ssh-quick-keygen
@@ -1,35 +1,175 @@
 #!/usr/bin/env bash
 
-email="$@"
-target="${HOME}/.ssh/${email}"
+set -umeTE
+set +f
+set -o pipefail
+export IFS=$'\n'
 
-function terminate_fail() {
-    2>&1 echo -e "\x1b[1;38;5;160m${@}\x1b[0m"
-    show_usage
-    exit 1
+declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
+declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+declare -- this_script_path="${script_path}/${script_name}"
+declare -- stderr="$(mktemp)"
+
+on_exit() {
+    set +x
+    bash -c "exec 1>&2;
+set -umeTE; set +f; set -o pipefail;
+rm -f ${stderr@Q} &
+disown -a
+"
 }
 
-function show_usage() {
-    2>&1 echo -e "\n\x1b[1;38;5;220mUSAGE:\n\t\x1b[1;38;5;33m$(basename $0) <EMAIL>\x1b[0m"
-    exit 1
+on_ctrlc() {
+    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
+    exit 130
 }
+trap on_exit exit
+trap on_ctrlc hup
+trap on_ctrlc int
+trap on_ctrlc bus
+trap on_ctrlc segv
+trap on_ctrlc sys
 
-function validate() {
-    if [ -z "${email}" ]; then
-        terminate_fail missing EMAIL
-    elif ! 2>/dev/null echo -n "${email}" | 1>/dev/null grep @; then
-        terminate_fail invalid EMAIL
+declare -a argv=(${@})
+declare -i argc=${#argv[@]}
+declare -- arg=""
+declare -- argument=""
+declare -- field=""
+declare -- key=""
+declare -- line=""
+declare -- name=""
+declare -- filename=""
+declare -- filename_extension=""
+declare -- filename_base=""
+declare -- param=""
+declare -- path=""
+declare -- pos=""
+declare -- value=""
+declare -i code=0
+declare -i current=0
+declare -i index=0
+declare -i line_number=0
+declare -i lineno=0
+declare -i skip=0
+declare -- email=""
+declare -- passphrase=""
+declare -- target_secret_key="${HOME}/.ssh/${email}"
+declare -- target_public_key="${target_secret_key}.pub"
+declare -- target_secret_art="${target_secret_key}.art"
+declare -- username=""
+declare -- domain=""
+declare -- tld=""
+declare -- reverse_dns=""
+
+declare -r default_target_directory="${HOME}/.ssh"
+declare -- target_directory="${HOME}/.ssh"
+declare -- key_type="ed25519" # ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa
+declare -- key_type="ecdsa"   # ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa
+
+main() {
+    if [ ${argc} -eq 0 ]; then
+        1>&2 echo -e "[${script_name} error]" "missing argument: <EMAIL>"
+        exit 1
+    fi
+
+    for index in ${!argv[@]}; do
+        current=$(($index + 1))
+        arg="${argv[$index]}"
+        pos="$(printf '%*s of %s' ${#argc} ${current} ${argc})"
+        if [ -z "${email}" ]; then
+            if [[ "${arg}" =~ ^(([a-zA-Z0-9_.+-]+)@([a-zA-Z]+[a-zA-Z0-9._+-]*)[.]([a-zA-Z]+[a-zA-Z0-9-]*))$ ]]; then
+                username=${BASH_REMATCH[2]}
+                domain=${BASH_REMATCH[3]}
+                tld=${BASH_REMATCH[4]}
+                email=${BASH_REMATCH[1]}
+            else
+                1>&2 echo -e "[${script_name} warning]" "ignoring argument ${pos} because email already set to ${email@Q}"
+                continue
+            fi
+        elif [ -n "${email}" ] && [ -d "${arg}" ]; then
+            target_directory="$(path canon "${arg}" | sed -z -E 's/[\n]+//g')"
+            1>&2 echo -e "[${script_name} warning]" "argument ${pos} set target directory to ${target_directory}"
+        fi
+    done
+
+    if [ -n "${email}" ] && [ -n "${username}" ] && [ -n "${domain}" ] && [ -n "${tld}" ]; then
+        reverse_dns="${tld}.${domain}.${username}"
+        target_secret_key="${target_directory}/${reverse_dns}.key"
+        target_public_key="${target_secret_key}.pub"
+        target_secret_art="${target_secret_key}.art"
+    else
+        1>&2 echo -e "[${script_name} error]" "aborted due to invalid email"
+        return 1
+    fi
+
+    if [ -e "${target_secret_key}" ]; then
+        1>&2 echo -e "[${script_name} error]" "key already exists: ${target_secret_key@Q}"
+        exit 1
+    fi
+    if [ -e "${target_secret_art}" ]; then
+        1>&2 echo -e "[${script_name} error]" "key art already exists: ${target_secret_art@Q}"
+        exit 1
+    fi
+    if [ -e "${target_public_key}" ]; then
+        1>&2 echo -e "[${script_name} error]" "public key already exists: ${target_public_key@Q}"
+        exit 1
+    fi
+    local -i proceed=0
+    if [ -n "${passphrase}" ]; then
+        local -- choice=""
+        read -p $(printf "passphrase is not empty, do you wish to proceed?\n[N/y]: ") choice
+        case "${choice@L}" in
+            n | no | nope)
+                proceed=0
+                1>&2 echo -e "[${script_name} error]" "aborted due to not confirming passphrase"
+                return 1
+                ;;
+            y | yes | yep | sure)
+                proceed=1
+                ;;
+            *)
+                1>&2 echo -e "[${script_name} error]" "invalid choice ${choice@Q}"
+                return 1
+                ;;
+        esac
+    else
+        proceed=1
+    fi
+
+    if [ "${target_directory}" == "${default_target_directory}" ]; then
+        local -- choice=""
+        read -p $(printf "key will be written to ${target_directory}, do you confirm?\n[N/y]: ") choice
+        case "${choice@L}" in
+            n | no | nope)
+                proceed=0
+                1>&2 echo -e "[${script_name} error]" "aborted due to not confirming write to ${target_directory}"
+                return 1
+                ;;
+            y | yes | yep | sure)
+                proceed=1
+                ;;
+            *)
+                1>&2 echo -e "[${script_name} error]" "invalid choice ${choice@Q}"
+                return 1
+                ;;
+        esac
+    else
+        proceed=1
+    fi
+
+    if ((${proceed})); then
+        1>&2 echo -e "[${script_name} info]" "writing key to ${target_secret_key}"
+        ssh-keygen -t "${key_type}" -C "${email}" -N "${passphrase@Q}" -f "${target_secret_key}" -l >${target_secret_art}
+        cat "${target_public_key}"
+    else
+        1>&2 echo -e "[${script_name} error]" "aborted"
     fi
 }
-function main() {
-    validate
-    if [ ! -e "${target}.art" ] || [ ! -e "${target}" ] ; then
-        ssh-keygen -t ed25519 -C "${email}" -N "" -f "${target}" | tail -11 > "${target}.art"
-    # elif [ -e "${target}" ]; then
-    #     g o -n # ...TK ask whether user wants to retry
-    fi
-    # echo "${target/$HOME/\~}.pub: "
-    cat "${target}.pub"
-}
 
-main
+if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
+    main
+    exit 0
+else
+    1>&2 echo -e "${BASH_SOURCE[0]} appears to being used as a library by ${0@Q}"
+    exit 1
+fi
diff --git a/gabrielfalcao/opt/libexec/yesterday b/gabrielfalcao/opt/libexec/yesterday
--- a/gabrielfalcao/opt/libexec/yesterday
+++ b/gabrielfalcao/opt/libexec/yesterday
@@ -1,5 +1,56 @@
 #!/usr/bin/env bash
-set -e
+
+set -umeTE
+set +f
+set -o pipefail
+unset IFS
+export IFS=$'\n'
+
+declare -- script_name="$(basename "${BASH_SOURCE[0]}")"
+declare -- script_path="$(2>/dev/random 1>/dev/random cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+on_exit() {
+    set +x
+}
+
+on_ctrlc() {
+    1>&2 echo -e "\x1b[1;38;2;253;67;83m\rAborted with Ctrl-C\x1b[0m"
+    exit 130
+}
+trap on_exit exit
+trap on_ctrlc hup
+trap on_ctrlc int
+trap on_ctrlc bus
+trap on_ctrlc segv
+trap on_ctrlc sys
+
 declare -i now=$(date +%s)
 
-gdate +"%Y-%m-%d" --date=@$(( $now - (60 * 60  *24) ))
+declare -a argv=(${@})
+declare -i argc=${#argv[@]}
+
+declare -A natnum_map=()
+declare -a natnums=()
+declare -i index=0
+declare -i current=0
+declare -- arg=""
+declare -- key=""
+declare -- val=""
+
+declare -i mul=1
+if [[ ! -v mul ]]; then
+    declare -i mul=1
+fi
+
+for index in ${!argv[@]}; do
+    current=$((index + 1))
+    arg=${argv[@]:${index}:1}
+    pos=$(printf '%*s of %d' "${#argc}" "${current}" "${argc}")
+    if [ ${mul} -le 1 ] && [[ ${arg} =~ ^[[:space:]]*(([1-9])([0-9]*))[[:space:]]*$ ]]; then
+        declare -i mul=${BASH_REMATCH[1]}
+    # elif [[ -v BASH_REMATCH ]]; then
+    #     declare -p BASH_REMATCH
+    fi
+done
+
+gdate +"%Y-%m-%d" --date=@$((now - (60 * 60 * 24 * ${mul})))
